### ISSUE TITLE
junos_cli :  Failing to return all data for "show system core-dumps" when output is text.

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/ansible-junos-stdlib#144]
The following is failing to collect all the core dump information:
```
- name: Create_core_dumps
  ignore_errors: False
  junos_cli:
    host: "{{ inventory_hostname }}"
    user: "{{ netconf_user }}"
    port: "{{ netconf_port }}"
    passwd: "{{ netconf_passwd }}"
    cli: "show system core-dumps all-members"
    dest: "{{ xml_dir }}/UPG_PRE_{{ inventory_hostname}}_core_dumps.txt"
    format: text
```

This produces only the output shown below:
```
fpc0:
--------------------------------------------------------------------------
```

Whereas, if the output format is xml the data is returned.
```
- name: Create_core_dumps_xml
  ignore_errors: False
  junos_cli:
    host: "{{ inventory_hostname }}"
    user: "{{ netconf_user }}"
    port: "{{ netconf_port }}"
    passwd: "{{ netconf_passwd }}"
    cli: "show system core-dumps all-members"
    dest: "{{ xml_dir }}/UPG_POST_{{ inventory_hostname}}_core_dumps.xml"
    format: xml
```
Produces the output
```
<multi-routing-engine-results>

<multi-routing-engine-item>

<re-name>fpc0</re-name>

<directory-list root-path="/var/crash/*core*" seconds="1467665132" style="verbose">
<output>/var/crash/*core*: No such file or directory</output>
<output>/var/tmp/*core*: No such file or directory</output>
<output>/var/tmp/pics/*core*: No such file or directory</output>
<output>/var/crash/kernel.*: No such file or directory</output>
<output>/var/jails/rest-api/tmp/*core*: No such file or directory</output>
</directory-list>
</multi-routing-engine-item>

<multi-routing-engine-item>

<re-name>fpc1</re-name>

<directory-list root-path="/var/crash/*core*" seconds="1467665132" style="verbose">
<output>/var/crash/*core*: No such file or directory</output>
<output>/var/tmp/*core*: No such file or directory</output>
<output>/var/tmp/pics/*core*: No such file or directory</output>
<output>/var/crash/kernel.*: No such file or directory</output>
<output>/var/jails/rest-api/tmp/*core*: No such file or directory</output>
</directory-list>
</multi-routing-engine-item>

<multi-routing-engine-item>

<re-name>fpc2</re-name>

<directory-list root-path="/var/crash/*core*" seconds="1467665132" style="verbose">
<output>/var/crash/*core*: No such file or directory</output>
<output>/var/tmp/*core*: No such file or directory</output>
<output>/var/tmp/pics/*core*: No such file or directory</output>
<output>/var/crash/kernel.*: No such file or directory</output>
<output>/var/jails/rest-api/tmp/*core*: No such file or directory</output>
</directory-list>
</multi-routing-engine-item>

<multi-routing-engine-item>

<re-name>fpc3</re-name>

<directory-list root-path="/var/crash/*core*" seconds="1467665133" style="verbose">
<output>/var/crash/*core*: No such file or directory</output>
<output>/var/tmp/*core*: No such file or directory</output>
<output>/var/tmp/pics/*core*: No such file or directory</output>
<output>/var/crash/kernel.*: No such file or directory</output>
<output>/var/jails/rest-api/tmp/*core*: No such file or directory</output>
</directory-list>
</multi-routing-engine-item>

<multi-routing-engine-item>

<re-name>fpc4</re-name>

<directory-list root-path="/var/crash/*core*" seconds="1467665133" style="verbose">
<output>/var/crash/*core*: No such file or directory</output>
<output>/var/tmp/*core*: No such file or directory</output>
<output>/var/tmp/pics/*core*: No such file or directory</output>
<output>/var/crash/kernel.*: No such file or directory</output>
<output>/var/jails/rest-api/tmp/*core*: No such file or directory</output>
</directory-list>
</multi-routing-engine-item>

</multi-routing-engine-results>
```
