### ISSUE TITLE
Syntax error while loading playbook with Junos role

### ISSUE THREAD

**Issue by tineg** [Juniper/ansible-junos-stdlib#189]
Hello,

I'm facing issues whille trying to configure a QFX5100 (v14.1) via ansible (VM Ubuntu 16.04).
The following error appears and I coudn't find an error in the yaml file I use.

Basic connectivity seems OK:
![image](https://cloud.githubusercontent.com/assets/11416706/20855499/f7ce7c6e-b8fd-11e6-92b9-af64b3d6c43f.png)

junos_install_config yaml and configuration file content:
![image](https://cloud.githubusercontent.com/assets/11416706/20855534/46debbca-b8fe-11e6-9521-20389d47b8d5.png)

Error:
![image](https://cloud.githubusercontent.com/assets/11416706/20855557/a0ed4f64-b8fe-11e6-94b1-27f73b657ca7.png)

Another one using junos_get_config:

![image](https://cloud.githubusercontent.com/assets/11416706/20855606/714fe11c-b8ff-11e6-9725-1c0a73086930.png)

Juniper.junos role has been downloaded and I checked several times that the dependencies were satisfied.
Perhaps am I missing something?
But as the first playbook work I don't understand what kind of misconfiguration could generate this error.

Thanks in advance for your help.

**Comment by dgarros** [comment]
Hi 

Yaml is very strict on indentation and tab.  apparently you're YAML files are not valid.

In the first example, you need to indent host and file like that
```yaml
  tasks:
    - junos_get_config:
         host: "{{inventory_hostname}}"
         file: myfile.conf
```

For the second issue, I would recommend to check for TAB, these are forbidden in Yaml.  
Also it looks like the line -junos_get_config is not properly indented neither

**Comment by tineg** [comment]
Thank you Damien,

I checked for TAB or identation problem. The get-config.yml is copy/paste from [http://junos-ansible-modules.readthedocs.io/en/1.3.0/junos_get_config.html](url).

![image](https://cloud.githubusercontent.com/assets/11416706/20855838/34082270-b903-11e6-8bcd-b3f13d5ace85.png)

Thank you in advance for your help.

**Comment by dgarros** [comment]
The indentation of your file is still incorrect, also you don't need a `-` before `junos_get_config` if you define `name`.  As it, it consider that `name` is a task

Try this one
```yaml
  tasks:
     - name: Get Junos Config
        junos_get_config:
          host: "{{ inventory_hostname }}"
          logfile: get_config.log
          dest: "{{ inventory_hostname }}.xml"
          format: xml
          filter: "interfaces"
          options: {inherit: inherit, groups: groups}
```

_I like the name of your host, I've been living in lyon for many years :)_

**Comment by tineg** [comment]
Hey, glad to hear that you live in Lyon. It's a nice coincidence ;-)
This host is just for a LAB and it's gonna go back to his home in Amsterdam.
But I think that sooner or later its entire family (it has big brothers ;-) is gonna move to Lyon for real.

Still the same message though with your correrction:

![image](https://cloud.githubusercontent.com/assets/11416706/20855994/83c62fb2-b905-11e6-944b-68a2d4feaf53.png)

But I think we're getting close to the correct syntax.

Thank you

**Comment by dgarros** [comment]
You still have an indentation issue, check my example and your file, they are different.
`name` and `junos_get_config` needs to be perfecctly aligned

**Comment by tineg** [comment]
Damien,

You're right.
After this last correction the code seems OK in different Yaml online validators:

![image](https://cloud.githubusercontent.com/assets/11416706/20858991/81df8eda-b952-11e6-865c-0c3585534f17.png)

But guess what, I'm still getting an error by launching it:
![image](https://cloud.githubusercontent.com/assets/11416706/20859009/e1bd6bf6-b952-11e6-9e88-603d92506fc6.png)

Here is the code:
```yaml
- name: GET config
  hosts: LYON4
  roles:
  - Juniper.junos
  
  tasks:
     - name: Get Junos Config
       junos_get_config:
       host: "{{ inventory_hostname }}"
       logfile: get_config.log
       dest: "{{ inventory_hostname }}.xml"
       format: xml
       filter: "interfaces"
       options: {inherit: inherit, groups: groups}
```

I'm wondering if the syntax problem doesn't hide another.

Thank you again for helping me,
