### ISSUE TITLE
rpc call on junos_zeroize hangs playbook

### ISSUE THREAD

**Issue by networkfoo** [Juniper/ansible-junos-stdlib#199]
whilst 'request system zeroize' is invoked correctly and run on target device, it does not return anything and hangs playbook when invoked via console 
<pre>
        use_notifier(None, 'ZEROIZE', 'invoking command')
        <b>dev.cli('request system zeroize')</b>
        results['changed'] = True
</pre>
This is not a problem via netconf ssh.

`ansible-junos-stdlib 1.4.0` `junos-eznc (2.0.1)`

**Comment by stacywsmith** [comment]
Please retest this using the new `juniper_junos_system` module introduced in #283.

The syntax should be:
```
- name: Zeroize via console
     juniper_junos_system:
       host: "{{ console_server }}"
       mode: "telnet"
       port: "{{ console_tcp_port }}"
       user: "{{ user }}"
       passwd: "{{ passwd }}"
       action: "zeroize" 
```

I believe the issue should now be fixed, but would appreciate your confirmation. Please reopen this issue if it's not fixed.
