### ISSUE TITLE
ImportError: No module name jnpr.junos OSX

### ISSUE THREAD

**Issue by japaho** [Juniper/ansible-junos-stdlib#245]
Getting this error, PyEz installed, and reinstalled. Ansible reinstalled. Any ideas?

Error from ansible-playbook:
```
TASK [Install Junos OS package] **********************************************************************************************************************************************************************************
fatal: [192.168.2.17]: FAILED! => {"changed": false, "failed": true, "msg": "ImportError: No module named jnpr.junos"}
```

```
$ ansible-galaxy list
- Juniper.junos, 1.4.2
```

```
$ python --version
Python 2.7.13
```

```
>>> import jnpr.junos
>>> jnpr.junos.__version__
'2.1.3'
>>> 
```

```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by ntwrkguru** [comment]
How are you calling the role in the playbook?

It should be:

```yaml
---
- name: foo
   roles:
   - Juniper.junos
```

From the error, it appears you are calling it as `jnpr.junos`.

**Comment by japaho** [comment]
Already in there, apologies:

```
- name: Install Junos OS
  hosts: extest
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    wait_time: 3600
    pkg_dir: /var/tmp
    OS_version: 15.5R5.5
    OS_package: jinstall-ex-2200-15.1R5.5-domestic-signed.tgz
    log_dir: /var/log/ansible

  vars_files:
  - /etc/ansible/vault-vars.yml

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=15

  - name: Install Junos OS package
    junos_install_os:
      host={{ inventory_hostname }}
      user={{ ROOT_USER }}
      passwd={{ ROOT_PASSWORD }}
      reboot=yes
      version={{ OS_version }}
      package={{ pkg_dir }}/{{ OS_package }}
      logfile={{ log_dir }}/software.log
    register: sw
    notify:
    - wait_reboot

  handlers:
  - name: wait_reboot
    wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
    when: not sw.check_mode
```

**Comment by ntwrkguru** [comment]
Where is your python?

**Comment by japaho** [comment]
$ type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python

$ ls -l /usr/local/bin/python
lrwxr-xr-x  1 root  wheel  68 26 May 10:32 /usr/local/bin/python -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python

**Comment by ntwrkguru** [comment]
You'll need to set `ansible_python_interpreter` in your playbook or inventory.

```yaml
- hosts: extest
  vars:
    ansible_python_interpreter: /usr/local/bin/python
```
