### ISSUE TITLE
Passing arguments to table/views

### ISSUE THREAD

**Issue by ymitsos** [Juniper/ansible-junos-stdlib#260]
Hi,

Is somehow supported passing arguments to a table/view call? For instance, one might want to fetch a route of a specific prefix instead of the whole routing table, is there any way to achieve this?

**Comment by vnitinv** [comment]
@ymitsos For now this is not doable with existing tables. I will try to do the required changes. But you can write/edit your custom table/view where itself such parameters (using args) can be passed. For example:

```yaml
---
EthPortTable:  
  rpc: get-interface-information
  args:
    media: True
    interface_name: ge-x/x/x
  args_key: interface_name
  item: physical-interface
  view: EthPortView
```
Do let me know if you face problem with this
