### ISSUE TITLE
Update config

### ISSUE THREAD

**Issue by ric79** [Juniper/ansible-junos-stdlib#289]
Hello,
I'm opening this issue not for a bug but because I need help about using the commands:
I wrote two playbooks which create the main config of a QFX node. 

The first one "reset" the node to a basic config:
```
      - name: Pushing config ... please wait
        junos_config:
          lines:
          - delete vlans
          - delete switch-options
          - delete routing-instances
          - delete firewall
          - delete class-of-service
          ...
          - set system host-name xxx-leaf-01
          - set system management-instance
          - set system root-authentication encrypted-password "xxx"
          - set system login user netconfadmin uid 2000
          - set system login user netconfadmin class super-user
          - set system login user netconfadmin authentication encrypted-password "xxxx"
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          ....
          update: merge
          comment: "Applied by Ansible (RESET)"
          provider: "{{ credential }}"
        register: result
```

The second one looks like:
```
    - name: "Pushing config ... please wait"
      junos_config:
        src: "{{ network_creation_conf }}"
        update: merge
        src_format: text
        comment: "Applied by Ansible"
        provider: "{{ credential }}"
      register: result
```
and the config file looks like this snippet: 
```
...
system {
    host-name xxx-leaf-01;
    domain-name xxx.it;
    time-zone Europe/Rome;
    services {
        ftp;
        netconf {
            ssh;
        }
        ssh {
            root-login deny;
            protocol-version v2;
        }
    }
}
...
```

How can I merge these two playbooks and in one transaction reset-and-update the QFX node? 

Thanks
