### ISSUE TITLE
Juniper Junos OS : Allow Routing engine selection for install OS 

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#292]
Current Junos CLI allows user to select RE on which image install has to take place.
To be on the same page, allow Ansible user to specify RE, if not specified current routing engine to be taken as default.

Present behaviour:

1. request system software add <PATH/PKG> re0 . ..> installs on RE0
2. request system software add <PATH/PKG> re1 .. >> Installs on RE1
3. request system software add <PATH/PKG> >> Not specified, installs on the local RE(master if run from master and BKP if run from backup RE)

**Comment by stacywsmith** [comment]
@mamathac This is a new feature request. It will require an enhancement to PyEZ first.

**Comment by NicoJNPR** [comment]
Hi.
Is it now planned?

**Comment by vnitinv** [comment]
@NicoJNPR  Let me bring up this next week and will plan for development.

**Comment by ntwrkguru** [comment]
@NicoJNPR This will also require an upstream enhancement to the underlying NETCONF RPC.

**Comment by dpajin** [comment]
@mamathac, @NicoJNPR, @vnitinv, @ntwrkguru, analyzing code of our Ansible libraries and PyEZ, it should be possible to specify which routing engine you want to install software package, thankfully to the kwargs argument that is cleverly transferred from Ansible to PyEZ and further in the SW library. 

So the playbook task can look like this for example (specify RE1 to install software in kwargs):

```
    - name: "Install software on RE1"
      juniper_junos_software:
        provider: "{{ credentials }}"
        local_package: 'package.tgz'
        cleanfs: false
        all_re: false
        reboot: false
        kwargs:
          re1: true
      register: response
```

I have tested this and it works for me (PyEZ 2.2.0)
