### ISSUE TITLE
"show configuration | display set" no longer works with junos_cli

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/ansible-junos-stdlib#297]
The following playbook previously worked to retrieve the committed configuration in set format:
```
---
- name: JUNOS CLI commands
  hosts: "{{ target }}"
  connection: local
  gather_facts: yes
  roles:
    - Juniper.junos
  vars:
    ask_vault_pass: False
    netconf_user:
    netconf_password:
    default_port: 22
    config_dir: CONFIGS
  tasks:
    - name: GET CONFIGURATION FROM {{ target }}
      junos_cli:
        host: "{{ inventory_hostname }}"
        cli: "show configuration | display set"
        logfile: "cli.log"
        dest: "{{ config_dir }}/{{ inventory_hostname }}.setconfig.txt"
        format: text
```

In general, pipe modifiers such as `| match`, or `| count` did not work with the `junos_cli` module because the underlying `<command>` RPC which the module uses doesn't support most pipe modifiers. In the past, these modifiers caused the module to produce a rather confusing error.

When the module was rewritten to `juniper_junos_command`, an additional check was added for these pipe modifiers in order to print a more meaningful error message.

This check was too broad and now causes the previously working `| display` modifiers to produce an error like this:
```
fatal: [192.168.2.185]: FAILED! => {"changed": false, "failed": true, "msg": "The pipe modifier (| display set) in the command (show configuration | display set) is not supported."}
```

The check needs to be relaxed to again allow `| display` modifiers.
