### ISSUE TITLE
Ansible Junos_rpc module multiple RPCS kwarg=None

### ISSUE THREAD

**Issue by RedLine89** [Juniper/ansible-junos-stdlib#334]
Hello,

I am trying to pack multiple RPCs into on one "query" to save some cycles.

As per "juniper_junos_rpc" documentation there should be a one-to-one correspondence between the elements in the kwargs list and the RPCs in the rpcs list, which is fair, but it is problematic if some RPCs require not a single argument.

Example:
```
  tasks:
  - name: Get Junos device information
    juniper_junos_rpc:
      host: "{{ inventory_hostname }}" 
      rpcs:
        - get-ethernet-switching-interface-information
        - get-vlan-information
        - get-interface-information
      kwargs:
        - brief: True
        - terse: True
        - ???????
      dest: pre-checks.output
    register: junos
```
I am looking to get "show interfaces" (get-interface-information) output as part of the list of RPCs and it needs no arguments.

I tried putting None, True, False etc., but the module fails to interpret arguments in the third item in the list.

Could you please add this functionality as per Stacy's [reply](https://groups.google.com/d/msg/junos-python-ez/Zu9jtmQIhSU/yeFDJ6ONAQAJ).

Thank you.
