### ISSUE TITLE
Configuration not complete when using juniper_junos_facts

### ISSUE THREAD

**Issue by imkwx** [Juniper/ansible-junos-stdlib#335]
Hi!

I am currently trying to get the configuration using juniper_junos_facts (because I don't want/need to save it locally), but when I try to get the config of a EX2200-C, I only get the first line of the configuration :
```json 
"config": "\n## Last commit: 2018-01-30 11:05:47 CET by xxxx\nsystem {\n    domain-name example.net;\n}\n",
```

Here's the playbook I'm using:
```yaml 
  hosts: switches
  roles:
        - Juniper.junos
  gather_facts: no
  connection: local
  vars_prompt:
        - name: "switch_user"
          prompt: "User "
          private: no
        - name: "switch_passwd"
          prompt: "Password "
          private: yes
  tasks:
    - name: Get Junos Facts
      juniper_junos_facts:
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ switch_user }}"
          password: "{{ switch_passwd }}"
          port: 22
          timeout: 30
        config_format: xml
      register: junos
      tags:
              - always
```

I can't reproduce this on switches like EX3300 or EX4300. 

Any ideas where this is coming from?

Thanks for the modules they're so nice :D 👌
