### ISSUE TITLE
juniper_junos_command truncated

### ISSUE THREAD

**Issue by ric79** [Juniper/ansible-junos-stdlib#341]
Hello,
If I execute: 
```
    - name: "Get running config"
      juniper_junos_command:
        cli: "show configuration"
        host: "{{ ansible_ssh_host }}"
        port: "{{ netconf_port }}"
        user: "{{ ansible_ssh_user }}"
        passwd: "{{ ansible_ssh_pass }}"
        dest: " "..........."
        format: "text"
      no_log: true
```

I get the configuration truncated (non all lines). Same result if I use `junos_cli` or if I use a `register` variable

At the moment I'm using:
```
    try:
        dev = Device(host=_host, user=_user, passwd=_password, console_has_banner=True)
        dev.open()
    except ConnectError as err:
        print ("Cannot connect to device: {0}".format(err))
        sys.exit(1)

    with open(_Junos__runningConfigFullname, 'w') as out_file:
       data = dev.rpc.get_config(options={'format':'text'})
       out_file.write(data.xpath('//configuration-text')[0].text)

    dev.close()
```
There are 2500 lines of configuration. File size: 65KB

```
ls -la ./etc/ansible/roles/Juniper.junos/library/juniper_junos_command.py
21791 Feb 19 17:12 
```

Riccardo

**Comment by ric79** [comment]
At the moment the only way is:
```
    - name: "Get running config"
      juniper_junos_rpc:
        host: "{{ ansible_ssh_host }}"
        port: "{{ netconf_port }}"
        user: "{{ ansible_ssh_user }}"
        passwd: "{{ ansible_ssh_pass }}"
        rpc: "get-config"
        return_output: false
        attr:
          format: "text"
        dest: "......."
      no_log: true

```

**Comment by stacywsmith** [comment]
Why not just use the `juniper_junos_config` module to retrieve the configuration?

Something like:
```
  tasks:
    - name: 'Retrieve the committed configuration'
      juniper_junos_config:
        retrieve: 'committed'
        format: 'text'
        diff: false
        check: false
        commit: false
        return_output: false
        dest: "......."
```

Is there any error produced when you receive the truncated configuration with `juniper_junos_command`?

Also, remember that the default timeout value (the maximum number of seconds to wait for RPC responses from the Junos device) is 30 seconds. You can increase this with the `timeout` option.
