### ISSUE TITLE
junos vlan table not returned

### ISSUE THREAD

**Issue by networkpadawan** [Juniper/ansible-junos-stdlib#351]
running ansible 2.5, junos modules 2.0.2 on "14.1X53-D40.8" switch i´m not able to get the output of the vlan list.

playbook:
```
---
- name: Get device facts
  hosts: junos_hosts
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve Vlan table
      juniper_junos_table:
        host: "{{ ansible_host }}"
        file: "vlan.yml"
      register: response
    - name: Print response
      debug:
        var: response
```
result:
```
ok: [SW1] => {
    "response": {
        "changed": false,
        "failed": false,
        "msg": "Successfully retrieved 0 items from VlanTable.",
        "resource": []
    }
}
```

**Comment by vnitinv** [comment]
@networkpadawan I would need you VLAN o/p from device to debug. Can you unicast me the xml data?

**Comment by networkpadawan** [comment]
@vnitinv how can I get that info? I only get the output shown above.

**Comment by vnitinv** [comment]
on junos device, run below command and share (can unicast to jnpr-community-netdev@juniper.net)

`show vlans | display xml`

**Comment by networkpadawan** [comment]
I think it might have to do with ELS syntax, but not sure.

**Comment by rsmekala** [comment]
@networkpadawan could you try using the following custom table/view in your vlan.yml .

vlan.yml
```
VlanTable:
  rpc: get-vlan-information
  item: l2ng-l2ald-vlan-instance-group
  key:  l2ng-l2rtb-vlan-tag
  view: VlanView

VlanView:
  fields:
    name: l2ng-l2rtb-name
    tag: l2ng-l2rtb-vlan-tag
    members: .//l2ng-l2rtb-vlan-member-interface
```
