### ISSUE TITLE
juniper_junos_software: lack of error on QFX when previous upgrade staged

### ISSUE THREAD

**Issue by fooelisa** [Juniper/ansible-junos-stdlib#352]
Hi,

I am upgrading QFX10002 devices though juniper_junos_software with the following scenario:
- the device has 15.1X53-D64.3 installed
- 15.1X53-D66.8 has been previously staged for upgrade (but no reboot has been issued)
- an ansible playbook tries to stage 17.3R2-S1.2 and reboot

The play reports that 17.3R2-S1.2 has been staged successfully. However upon reboot, the device comes back with version 15.1X53-D66.8, instead of 17.3R2-S1.2.
```
TASK [jinstall-stage : Starting upgrade to version 17.3R2-S1.2] ***
task path: /opt/viki/ansible/roles/jinstall-stage/tasks/stage.yml:45
Using module file /opt/ansible-junos-stdlib/Juniper.junos/library/juniper_junos_software.py
<cfr1.lab1> ESTABLISH LOCAL CONNECTION FOR USER: elisa
<cfr1.lab1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [cfr1.lab1] => {
    "changed": true,
    "check_mode": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "force_host": false,
            "host": "cfr1.lab1",
            "issu": false,
            "logdir": null,
            "logfile": "/var/log/viki/upgrade_junos_cfr1.lab1.log",
            "mode": null,
            "nssu": false,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "provider": null,
            "ssh_private_key_file": null,
            "timeout": 30,
            "user": "viki",
            "validate": false,
            "vmhost": false
        },
        "module_name": "juniper_junos_software"
    },
    "msg": "Package jinstall-host-qfx-10-f-x86-64-17.3R2-S1.2-secure-signed.tgz successfully installed."
}
```
When done manually on the command line, I get an error that another upgrade is in progress, as expected:
```
elisa@cfr1.lab1> request system software add /var/tmp/jinstall-host-qfx-10-f-x86-64-17.3R2-S1.2-secure-signed.tgz
Verified jinstall-host-qfx-10-f-x86-64-17.3R2-S1.2-secure-signed signed by PackageProductionSwitchingEc_2015
Pushing Junos image package to the host...
There is pending upgrade. upgrade_in_progress=stage
Please reboot the system to complete the installation or rollback before attempting another upgrade

{master:0}
elisa@cfr1.lab1>
```
On other device models, the ansible play also reports an error when an upgrade has previously been staged, eg. on an MX:
```
TASK [jinstall-stage : Starting upgrade to version 17.1R2-S5] ***
task path: /opt/viki/ansible/roles/jinstall-stage/tasks/stage.yml:45
Using module file /opt/ansible-junos-stdlib/Juniper.junos/library/juniper_junos_software.py
<mx1.lab1> ESTABLISH LOCAL CONNECTION FOR USER: elisa
<mx1.lab1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [mx1.lab1]: FAILED! => {
    "changed": true,
    "check_mode": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "force_host": false,
            "host": "mx1.lab1",
            "issu": false,
            "logdir": null,
            "logfile": "/var/log/viki/upgrade_junos_mx1.lab1.log",
            "mode": null,
            "nssu": false,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "provider": null,
            "ssh_private_key_file": null,
            "timeout": 30,
            "user": "viki",
            "validate": false,
            "vmhost": false
        },
        "module_name": "juniper_junos_software"
    },
    "msg": "Unable to install the software"
}
```
Could this be an issue with error reporting specifically on QFX?

My task looks like this:
```
  - name: Starting upgrade to version {{ vars[version].os_version }}
    juniper_junos_software:
      host: "{{ device_name }}"
      user: "{{ user }}"
      passwd: "{{ passwd }}"
      port: "{{ netconf_port }}"
      no_copy: true
      cleanfs: no
      reboot: false
      all_re: true
      validate: "{{ validate|bool }}"
      version: "{{ vars[version].os_version }}"
      remote_package: "{{ remote_file }}"
      logfile: "/var/log/viki/upgrade_junos_{{ device_name }}.log"
```

Thanks
Elisa
