### ISSUE TITLE
ERROR! the handler 'juniper_junos_software' was not found.

### ISSUE THREAD

**Issue by Nexus-Neraian** [Juniper/ansible-junos-stdlib#353]
# inventory
```ini
device1 ansible_host=1.1.1.1 target_junos="junos-install-mx-x86-64-17.4R1.16.tgz"

[all:vars]
ansible_connection="local"
ansible_user="babalah"
ansible_password="12345678"
```
# playbook
```yaml
---
- name: Junos Upgrade
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        host: "{{ansible_host}}"
        cleanfs: false
        local_package: "./{{target_junos}}"
      register: response

    - name: Print the complete response.
      debug:
        var: response
```

# Error message
```
nexus@ubuntu:~/Junos-Upgrade-Only$ ansible-playbook -i inventory upgrade.yaml -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in upgrade.yaml

PLAY [Junos Upgrade] ***********************************************************

TASK [Execute a basic Junos software upgrade.] *********************************
task path: /home/nexus/Junos-Upgrade-Only/upgrade.yaml:9
fatal: [device1]: FAILED! => {"failed": true, "msg": "ERROR! the handler 'juniper_junos_software' was not found"}

PLAY RECAP *********************************************************************
device1                    : ok=0    changed=0    unreachable=0    failed=1 
```
