### ISSUE TITLE
Did not find expected response from reboot RPC

### ISSUE THREAD

**Issue by sergeysj** [Juniper/ansible-junos-stdlib#377]
TASK [Install Junos OS package] ***********************************************************************************
fatal: [HOSTNAME]: FAILED! => {"changed": true, "check_mode": false, "msg": "Package /apps/software/junos/jinstall-ex-4300-14.1X53-D47.3-domestic-signed.tgz successfully installed. Did not find expected response from reboot RPC."}
        to retry, use: --limit @/home/username/ansible-playbooks/junos-install-os-vault.retry

PLAY RECAP ********************************************************************************************************
HOSTNAME: ok=2    changed=0    unreachable=0    failed=1

log file
[Jun 16 08:57:40]: Checking pending install on fpc4

Pushing /var/tmp/jinstall-ex-4300-14.1X53-D47.3-domestic-signed.tgz to fpc4:/var/tmp/jinstall-ex-4300-14.1X53-D47.3-domestic-signed.tgz
Verify the signature of the new package
Verified jinstall-ex-4300-14.1X53-D47.3-domestic.tgz signed by PackageProductionRSA_2018
WARNING: A reboot is required to install the software
WARNING:     Use the 'request system reboot' command immediately
2018-06-16 08:58:38,931 - ncclient.operations.rpc - INFO - Requesting 'ExecuteRpc'
2018-06-16 08:58:40,499 - ncclient.operations.rpc - INFO - Requesting 'CloseSession'

switch restarts however playbook exits

Juniper EX4300 output

*** FINAL System shutdown message from remote@HOSTNAME***              
System going down IMMEDIATELY                                                  
                                                                               
Message from syslogd@HOSTNAME at Jun 16 08:59:45.773 2018 ...
HOSTNAME pfex: CMLC: Going disconnected; Routing engine chassis socket closed abruptly

Issue Type
------
 - Bug Report

Module Name
------

Juniper.Junos role and Python libraries version
 ansible --version
ansible 2.5.4
  config file = /home/username/.ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 16 2017, 13:14:28) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]

Also provide the version of Juniper.junos role-->
 ansible-galaxy list
- Juniper.junos, (unknown version)

OS / Environment
------
Red Hat Enterprise Linux Server release 6.9 (Santiago)

Summary
------
Error message Did not find expected response from reboot RPC

Steps to reproduce
------

```yaml
    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        validate: true
        logfile: "{{ log_dir }}/software.log"
      register: sw

    - name: pause_for_reboot
      pause:
        seconds: 180
      when: not sw.check_mode

    - name: wait_reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode

```

Expected results

```

```
Actual results
------

```
fatal: [HOSTNAME]: FAILED! => {
    "changed": true,
    "check_mode": false,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "force_host": false,
            "host": "HOSTNAME",
            "issu": false,
            "logdir": null,
            "logfile": "/var/log/ansible/software.log",
            "mode": null,
            "nssu": false,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "provider": null,
            "ssh_private_key_file": null,
            "timeout": 30,
            "user": "user",
            "validate": true,
            "vmhost": false
        }
    },
    "msg": "Package /apps/software/junos/jinstall-ex-4300-14.1X53-D47.3-domestic-signed.tgz successfully installed. Did not find expected response from reboot RPC."

```

**Comment by trustinger** [comment]
I have this same problem on Ansible 2.4.2, using Juniper.junos 2.1.0. 

```
TASK [code_upgrade : Upgrade Juniper devices] ***********************************************************
task path: /etc/ansible/new_test/.git/dev/code_upgrade/roles/code_upgrade/tasks/main2.yml:13
fatal: [lab-3]: FAILED! => {
    "changed": false,
    "module_stderr": "No handlers could be found for logger \"ncclient.transport.session\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_0fR5rt/ansible_module_juniper_junos_software.py\", line 747, in <module>\n    main()\n  File \"/tmp/ansible_0fR5rt/ansible_module_juniper_junos_software.py\", line 743, in main\n    junos_module.exit_json(**results)\n  File \"/tmp/ansible_0fR5rt/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 792, in exit_json\n  File \"/tmp/ansible_0fR5rt/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1327, in close\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/device.py\", line 1317, in close\n    self._conn.close_session()\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 162, in wrapper\n    return self.execute(op_cls, *args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 232, in execute\n    raise_mode=self._raise_mode).request(*args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/session.py\", line 28, in request\n    return self._request(new_ele(\"close-session\"))\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/rpc.py\", line 343, in _request\n    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')\nncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
```

**Comment by sergeysj** [comment]
@trustinger you have more than 1 member in the virtual-chassis right ?

**Comment by trustinger** [comment]
@sergeysj this is on an SRX550 and MX5. Seems to be related to the reboot because when I say “reboot: no” and insert another task below to do the reboot it works fine.

**Comment by macbinjo** [comment]
Hello,

are there any updates to this? Can this be declared as a bug?

**Comment by sergeysj** [comment]
@macbinjo What kind of device you are running this module on?

**Comment by arusso** [comment]
Seeing this exact issue as well on a EX4300 VC w/3 members when updating the VC to `16.1R7-S2` or back down to `14.1X53-D45.3`.

```
$ python -V
Python 2.7.13
$ ansible --version
ansible 2.7.0
  ...
  python version = 2.7.13 (default, May  1 2017, 09:51:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

Trying to execute the reboot as a separate task didn't work for me:

```
- name: Install Junos OS package
  juniper_junos_software:
    version: "{{ junos_version }}"
    local_package: "{{ junos_dir }}/{{ junos_package }}"
    reboot: false
    validate: true
    logfile: "{{ log_dir }}/software.log"
  register: sw

- name: Reboot switch after upgrade
  juniper_junos_system:
    action: reboot
  when: not sw.check_mode and sw.changed
```

Results in:

```
TASK [Install Junos OS package] **************************************************************************************************************************************************************************************************************
changed: [juniper-ex4300-lab-01.example.com]

msg: Package /dist/os/bsd/junos/ex4300/jinstall-ex-4300-16.1R7-S2-signed.tgz successfully installed.
Saturday 26 January 2019  21:18:51 -0800 (0:10:24.929)       0:10:25.539 ******

TASK [Reboot switch after upgrade] ***********************************************************************************************************************************************************************************************************
fatal: [juniper-ex4300-lab-01.example.com]: FAILED! => {"action": "reboot", "all_re": true, "changed": false, "media": false, "msg": "Did not find expected RPC response.", "other_re": false, "reboot": true}
```
