### ISSUE TITLE
juniper_junos_software - command is not valid on the mx40-t

### ISSUE THREAD

**Issue by eregimbald** [Juniper/ansible-junos-stdlib#381]
Issue Type
------
 - Bug Report

Module Name
------

juniper_junos_software

Juniper.Junos role and Python libraries version

```
ansible 2.4.2.0
  config file = /ansible/network-ansible/ansible.cfg
  configured module search path = [u'/home/eregimbald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

ansible==2.4.2.0
appdirs==1.4.3
asn1crypto==0.24.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.4
cffi==1.11.3
chainmap==1.0.2
chardet==2.2.1
colorama==0.3.9
configobj==4.7.2
configparser==3.5.0
cryptography==2.1.4
decorator==3.4.0
dnspython==1.15.0
ecdsa==0.13
enum34==1.1.6
ez-setup==0.9
future==0.16.0
httplib2==0.7.7
icdiff==1.9.1
idna==2.6
imageio==2.1.2
iniparse==0.4
ipaddress==1.0.19
Jinja2==2.8
jmespath==0.9.3
jsnapy==1.3.0
jtextfsm==0.3.1
junos-eznc==2.1.7
junos-netconify==1.0.2
jxmlease==1.0.1
kitchen==1.1.1
librouteros==1.0.2
lxml==4.1.1
MarkupSafe==1.0
moviepy==0.2.2.13
music21==3.1.0
mysql-connector-python-rf==2.2.2
napalm==1.2.0
napalm-base==0.23.2
napalm-eos==0.5.6
napalm-fortios==0.3.1
napalm-ios==0.6.1
napalm-iosxr==0.4.8
napalm-junos==0.6.6
napalm-nxos==0.5.1
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.2
napalm-vyos==0.1.3
ncclient==0.5.3
netaddr==0.7.19
netmiko==1.3.0
numpy==1.12.1
olefile==0.44
packaging==16.8
pan-python==0.10.0
paramiko==2.4.0
perf==0.1
Pillow==4.0.0
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.0
pyeapi==0.8.0
pyfg==0.47
pygobject==3.14.0
pygpgme==0.3
pyIOSXR==0.41
pyliblzma==0.5.3
PyNaCl==1.2.1
pynxos==0.0.3
pyparsing==2.2.0
pyPluribus==0.3.1
pyserial==3.4
python-keyczar==0.71rc0
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.12
requests==2.13.0
requests-toolbelt==0.7.1
scp==0.10.2
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
SSSDConfig==1.14.0
tqdm==4.11.2
unroll==0.1.0
urlgrabber==3.10
VyattaConfParser==0.4.4
xmltodict==0.10.2
yum-metadata-parser==1.1.4
```

OS / Environment
------

Freshly purchased MX40-T

Model: mx40-t
Junos: 15.1R6.7

Summary
------

Attempting to run a firmware upgrade to 15.7R7.8 gives me the error: 
command is not valid on the mx40-t

Steps to reproduce
------

Using juniper_junos_software to send this package: jinstall-ppc-15.1R7.8-export-signed.tgz
To an mx-40t

```yaml
---
# group_vars
firmware:
  EX2200-48T-4G: jinstall-ex-2200-12.3R12.4-domestic-signed.tgz
  MX40-T: jinstall-ppc-15.1R7.8-export-signed.tgz
  SRX345: junos-srxsme-15.1X49-D130.6-domestic.tgz
  SRX1500: junos-srxentedge-15.1X49-D140.2-domestic.tgz
  QFX5100-48S-6Q: jinstall-host-qfx-5-15.1R6.7-domestic-signed.tgz


---
- name: Software Update
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - Juniper.junos
  vars:
    playbook: Software Update
    commit: "True"
    comment: "Updating firmware for {{ target }}"

  vars_prompt:
    - name: "target"
      prompt: "Enter host or inventory group"
      private: no

  hosts: "{{target}}"

  tasks:
    - block:
      - include_role:
          name: Juniper.junos
      - include_role:
          name: base/workcomplete    # This sends the "comment" to Slack
      - name: Getting device facts      # Get the device model number
        juniper_junos_facts:
          host: '{{ inventory_hostname }}'
          user: '{{ user }}'
        register: results
        
      - debug: msg="{{results.ansible_facts.junos.model}}"
      
      - name: Installing software package
        juniper_junos_software:
          host: '{{ inventory_hostname }}'
          user: '{{ user }}'
          local_package: 'library/packages/{{firmware[results.ansible_facts.junos.model]}}'
          all_re: true
          cleanfs: false
          no_copy: false
          validate: false
          force_host: true
          reboot: true
  
    - rescue:
      - include_role:
          name: base/workfailed
          
# You need to have the image files stored in library/packages/

```
