### ISSUE TITLE
junos_config: compare integers in the waitfor statement

### ISSUE THREAD

**Issue by julienlorent** [Juniper/ansible-junos-stdlib#386]
Issue Type
------

 - Bug Report

Module Name
------
juniper_junos_config

Juniper.Junos role and Python libraries version

```
ansible 2.5.1
  config file = /root/tp1/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

ansible==2.5.1
apache-libcloud==2.2.1
asn1crypto==0.24.0
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.6.0
cached-property==1.3.1
certifi==2018.1.18
chardet==3.0.4
cryptography==2.1.4
docker==2.5.1
docker-compose==1.17.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
html5lib==0.999999999
httplib2==0.9.2
idna==2.6
ipaddress==1.0.17
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
junos-eznc==2.1.7
jxmlease==1.0.1
keyring==10.6.0
keyrings.alt==3.0
lockfile==0.12.2
lxml==4.2.1
MarkupSafe==1.0
mock==2.0.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.0.0
pbr==3.1.1
pyasn1==0.4.2
pycrypto==2.6.1
pygobject==3.26.1
pykerberos==1.1.14
pyOpenSSL==17.5.0
pyserial==3.4
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
scp==0.10.2
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
texttable==0.9.1
urllib3==1.22
webencodings==0.5
websocket-client==0.44.0
xmltodict==0.11.0
```

OS / Environment
------
Model: vmx
Junos: 18.1R1.9

Summary
------
Can't compare result string with integer

Steps to reproduce
------

```yaml
- name: Check vlans on junos
  hosts: vMX
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars_files:
  - "vlans.yml"

  tasks:
    - name: check vlans
      junos_command:
        provider:
          host: "{{ junos_host }}"
          username: "{{ SSH_USERNAME }}"
          password: "{{ SSH_PASSWORD }}"
          timeout: 20
        commands:
          - show bridge domain {{ item.name }}
        display: xml 
        waitfor:
          - "result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['
l2rtb-bridging-domain'] eq {{ item.name }}"
          - "result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['
l2rtb-bridge-vlan'] == {{ item.id }}"
      with_items: "{{ vlans }}"
```
And the vlans.yml
```yaml
vlans:
  - id: 100
    name: VLAN100
  - id: 300
    name: VLAN300
```

Expected result
```
ok: [vMX-1] => (item={u'id': 100, u'name': u'VLAN100'})
ok: [vMX-1] => (item={u'id': 300, u'name': u'VLAN300'})
```
Actual results
------

```
failed: [vMX-1] (item={u'id': 100, u'name': u'VLAN100'}) => {"changed": false, "failed_conditions": ["result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['l2rtb-bridge-vlan'] == 100"], "item": {"id": 100, "name": "VLAN100"}, "msg": "One or more conditional statements have not been satisfied"}
```

My workaround: using a combination of >= and <= operators:
```yaml
- name: Check vlans on junos
  hosts: vMX
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars_files:
  - "vlans.yml"

  tasks:
    - name: check vlans
      junos_command:
        provider:
          host: "{{ junos_host }}"
          username: "{{ SSH_USERNAME }}"
          password: "{{ SSH_PASSWORD }}"
          timeout: 20
        commands:
          - show bridge domain {{ item.name }}
        display: xml 
        waitfor:
          - "result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['
l2rtb-bridging-domain'] eq {{ item.name }}"
          - "result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['
l2rtb-bridge-vlan'] >= {{ item.id }}"
          - "result[0]['rpc-reply']['l2ald-bridge-instance-information']['l2ald-bridge-instance-group']['
l2rtb-bridge-vlan'] <= {{ item.id }}"
      with_items: "{{ vlans }}"
```

**Comment by rsmekala** [comment]
@julienlorent `junos_command` is not a module from Juniper.junos role, it is a Ansible core module. 

I don't know much about the core modules, but you could alternatively use `juniper_junos-table` to achieve the same.

### Playbook
```
---
- name: Retrieve data from a Junos device using a PyEZ table/view.
  hosts: vMX
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Retrieve Interface Information Using PyEZ-included Table
      juniper_junos_table:
        file: "interface.yml"
        path: "."
        kwargs:
          interface-name: cbp0
      register: response

    - name: Check correct vlan is retrieved
      assert:
        that:
          - "response['resource'][0]['Index'] == 129"
```

### TableView:
```
---
InterfaceTable:
  rpc: get-interface-information
  item: physical-interface
  key: name
  view: InterfaceView

InterfaceView:
  fields:
    Name: name
    Index: { local-index: int}

```
