### ISSUE TITLE
Connect to Same host with different ports

### ISSUE THREAD

**Issue by panks21** [Juniper/ansible-junos-stdlib#391]
Issue Type
------

  - Feature Idea

Module Name
------

Juniper.Junos role and Python libraries version

```
ansible 2.6.3
Juniper.junos 2.1
```

OS / Environment
------

```
Junos 17.3R3
```
Summary
------

```
Multiple Junos devices are behind a firewall and needs to connect via port forwarding on firewall like 
MX1 -- 126.129.235.1 port 44024
MX2 -- 126.129.235.1 port 44021
```
Steps to reproduce
------

```yaml
---
- name: Show Version
  gather_facts: yes
  connection: local
  roles:
    - Juniper.junos
  hosts: all

  tasks:
    - name: Show Version on Junos Device
      juniper_junos_command:
        commands: "show version"
        user: juniper
        passwd: Juniper!1
      register: response


Host File

[MX]
126.129.235.1 ansible_port=44024
126.129.235.1 ansible_port=44021
```

Expected results

```

```
Actual results
------

```
fatal: [126.129.235.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "attempts": null, 
            "baud": null, 
            "commands": [
                "show version"
            ], 
            "console": null, 
            "dest": null, 
            "dest_dir": null, 
            "formats": null, 
            "host": "126.129.235.1", 
            "level": null, 
            "logdir": null, 
            "logfile": null, 
            "mode": null, 
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 830, 
            "provider": null, 
            "return_output": true, 
            "ssh_config": null, 
            "ssh_private_key_file": null, 
            "timeout": 30, 
            "user": "jcluser"
        }
    }, 
    "msg": "Unable to make a PyEZ connection: ConnectTimeoutError(126.129.235.1)"
}
```
