### ISSUE TITLE
EX4300 Virtual Chassis Software upgrade or reboot fails 

### ISSUE THREAD

**Issue by anuragmenon2011** [Juniper/ansible-junos-stdlib#395]
Issue Type
------

 - Bug Report

Module Name
------

juniper_junos_software
juniper_junos_ssystem

Juniper.Junos role and Python libraries version

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]


ansible==2.6.3
asn1crypto==0.24.0
bcrypt==3.1.4
cffi==1.11.5
cryptography==2.3.1
ecdsa==0.13
enum34==1.1.6
httplib2==0.9.1
idna==2.7
ipaddress==1.0.22
Jinja2==2.8
junos-eznc==2.2.0
lxml==4.2.4
MarkupSafe==0.23
ncclient==0.6.2
netaddr==0.7.19
paramiko==2.4.1
pyasn1==0.4.4
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
pyserial==3.4
PyYAML==3.11
scp==0.11.0
selectors2==2.0.1
six==1.11.0
```

OS / Environment
------

EX-4300 Virtual Chassis Junos 14.1X53-D47.3

Summary
------

Ansible play to upgrade the software on EX 4300 virtual chassis fails. The software upgrade happens, and the reboot is issued, but the playbook exits ungracefully with the error:
"Did not find expected response from reboot RPC"

Steps to reproduce
------

Run the playbook pasted below on a EX 4300 non mixed virtual chassis with 2 devices. One RE and one Backup RE stacked together.

```yaml

---

  # Run play with -v so that it logs info as well as errors
  # Install takes about 10 Min and reboot takes about 30 min
- name: Install Junos
  hosts: junos
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    OS_version: "14.1X53-D47.3"
#    OS_version: "17.1R2.7"
    OS_package: "jinstall-ex-4300-14.1X53-D47.3-domestic-signed.tgz"
#    OS_package: "jinstall-ex-4300-17.1R2.7-signed.tgz"
    pkg_dir: "/var/tmp"
    log_dir: "/var/log"
    wait_time: 1200
    netconf_port: 830

  tasks:
    - name: Check NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"



    - name: Install Junos OS package
      juniper_junos_software:
        no_copy: true
       # nssu: true
        version: "{{ OS_version }}"
        remote_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: yes
        validate: true
        logfile: "{{ log_dir }}/{{ inventory_hostname }}-install.log"
      register: sw
#      notify:
      - pause_for_reboot
      - wait_reboot

    - name: Print response
      debug:
        var: sw

#    - name: Reboot alll Routing Engines
#      juniper_junos_system:
#        action: "reboot"
#        all_re: true
#        logfile: "{{ log_dir }}/{{ inventory_hostname }}-reboot.log"
#      register: result
#      notify:
#      - pause_for_reboot
#      - wait_reboot

#    - name: Print Response
#      debug:
#        var: result

  handlers:
    - name: pause_for_reboot
      pause:
        seconds: 300
      when: sw.reboot

    - name: wait_reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
```

Expected results

```
The playbook to complete without errors
```
Actual results
------

```
ansible-playbook 2.6.3
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /root/ansible/ansible.cfg as config file

PLAYBOOK: exvc-junos-up.yml ***************************************************************************
1 plays in exvc-junos-up.yml

PLAY [Install Junos] **********************************************************************************
META: ran handlers

TASK [Check NETCONF connectivity] *********************************************************************
task path: /root/ansible/exvc-junos-up.yml:23
ok: [poc-ex4300-35] => {"changed": false, "elapsed": 0, "path": null, "port": 830, "search_regex": null, "state": "started"}

TASK [Install Junos OS package] ***********************************************************************
task path: /root/ansible/exvc-junos-up.yml:30
fatal: [poc-ex4300-35]: FAILED! => {"changed": true, "check_mode": false, "msg": "Package jinstall-ex-4300-17.1R2.7-signed.tgz successfully installed. Did not find expected response from reboot RPC."}
	to retry, use: --limit @/root/ansible/exvc-junos-up.retry

PLAY RECAP ********************************************************************************************
poc-ex4300-35              : ok=1    changed=0    unreachable=0    failed=1
```
