### ISSUE TITLE
juniper_junos_software module failure _scp_progress  takes exactly 4 arguments (5 given)

### ISSUE THREAD

**Issue by doellal** [Juniper/ansible-junos-stdlib#405]
Issue Type
-----
 - Bug Report

Module Name
------
juniper_junos_software 

Juniper.Junos role and Python libraries version

```
ansible 2.4.2.0
junos-eznc==2.2.0
Juniper.junos role 2.1.0
```

OS / Environment
------

CentOS Linux release 7.5.1804 (Core)

Summary
------

I want to update a a Juniper SRX300 with the juniper_junos_software module. I update from junos-srxsme-15.1X49-D70.3-domestic.tgz version to junos-srxsme-15.1X49-D150.2-domestic.tgz. The Software is copied from the ansible host to the SRX300, but the scp in a python file gets a error for to many arguments. The connection is stabile and i have tried different timeouts. How can i fix the problem?

Steps to reproduce
------

```yaml
---
- name: Examples of juniper_junos_software
  hosts: juniper_live
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        host: "{{ inventory_hostname }}"
        port: "{{ sshport }}"
        user: "{{ username }}"
        passwd: "{{ password }}"
        version: "15.1X49-D150.2"
        local_package: "./software/junos-srxsme-15.1X49-D150.2-domestic.tgz"
        reboot: true
        validate: true
        logfile: "software.log"
```

Expected results

```
1. Connection
2. Check Software and copy
3. Check Software
4. Install Softwre
5. Reboot
6. Ok
```
Actual results
------

```
    "plays": [
        {
            "play": {
                "id": "005056a9-1fd2-0f28-9592-00000000000b",
                "name": "Examples of juniper_junos_software"
            },
            "tasks": [
                {
                    "hosts": {
                        "80.228.150.122": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": false,
                            "changed": false,
                            "module_stderr": "No handlers could be found for logger \"ncclient.transport.session\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_z7ujGW/ansible_module_juniper_junos_software.py\", line 747, in <module>\n    main()\n  File \"/tmp/ansible_z7ujGW/ansible_module_juniper_junos_software.py\", line 660, in main\n    ok = junos_module.sw.install(**install_params)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py\", line 842, in install\n    force_copy=force_copy)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py\", line 611, in safe_copy\n    self.put(package, remote_path=remote_path, progress=progress)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py\", line 194, in put\n    scp.put(package, remote_path)\n  File \"/usr/lib/python2.7/site-packages/scp.py\", line 166, in put\n    self._send_files(files)\n  File \"/usr/lib/python2.7/site-packages/scp.py\", line 270, in _send_files\n    self._send_file(fl, name, mode, size)\n  File \"/usr/lib/python2.7/site-packages/scp.py\", line 287, in _send_file\n    self._progress_tracker(self._progress, basename, size, 0, self.peername)\n  File \"/usr/lib/python2.7/site-packages/scp.py\", line 129, in _progress_tracker\n    method(basename, size, file_pos, peername)\nTypeError: _scp_progress() takes exactly 4 arguments (5 given)\n",
                            "module_stdout": "",
                            "msg": "MODULE FAILURE",
                            "rc": 0
                        }
                    },
                    "task": {
                        "id": "005056a9-1fd2-0f28-9592-000000000010",
                        "name": "Execute a basic Junos software upgrade."
                    }
                }
            ]
        }
    ],
    "stats": {
        "80.228.150.122": {
            "changed": 0,
            "failures": 1,
            "ok": 0,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```
Log File
```
2018-12-03 13:41:15,117 - ncclient.transport.ssh - DEBUG - EOF in transport thread
2018-12-03 13:41:15,117 - ncclient.transport.ssh - DEBUG - Broke out of main loop, error=SessionCloseError('Unexpected session close\nIN_BUFFER: `\n`',)
2018-12-03 13:41:15,117 - ncclient.transport.session - DEBUG - dispatching error to <jnpr.junos.device.DeviceSessionListener object at 0x7fb93f285310>
2018-12-03 13:41:15,118 - ncclient.transport.session - DEBUG - dispatching error to <ncclient.transport.session.NotificationHandler object at 0x7fb94070efd0>
2018-12-03 13:41:15,118 - ncclient.transport.session - DEBUG - dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7fb93f2855d0>
```
