### ISSUE TITLE
juniper_junos_command and juniper_junos_rpc dest/dest_dir add  option to add executed command inside the result file

### ISSUE THREAD

**Issue by CodeTechies** [Juniper/ansible-junos-stdlib#415]
juniper_junos_command and juniper_junos_rpc dest/dest_dir add an option that can add the executed command inside the result file.

Currently, if write output to a single file I can't identify from which output of the command was executed.
 

Issue Type
 - Feature Idea

Module Name

juniper_junos_command and juniper_junos_rpc
Juniper.Junos role and Python libraries version

**Comment by stacywsmith** [comment]
When using the `dest_dir` option the filename already includes the command/RPC which produced the content in the file. When these modules were enhanced to execute multiple commands/RPCs per invocation, the `dest_dir` option was added and the `dest` option was deprecated for exactly the purpose of correlating the command/RPC to its output.

In addition, when multiple commands/RPCs are executed and `return_output: false` is not set, then the return from these modules includes a `results` key with a list of results. Each item in that list is a dictionary, and that dictionary contains a `command` or `rpc` key indicating what command/RPC produced the corresponding results in the item's `parsed_output`, `stdout`, and `stdout_lines` keys.

I'm generally opposed to including the command/RPC in the content of the file(s) produced by the `dest` and `dest_dir` options for the following reasons:
1) This information is already included in the filename produced by the `dest_dir` option and in the `results` data structure returned from the module.
2) The `dest` option is deprecated precisely because it doesn't easily handle the output of multiple commands/RPCs. I don't believe a deprecated option should be enhanced.
3) A change in the `dest` and `dest_dir` output files contents would require subsequent tasks which consume these files to parse the command/RPC portion of the content from the output portion of the content. That's not an easy/reliable requirement given Ansible's capabilities.
4) The desired functionality could also be realized by combining the `juniper_junos_command` or `juniper_junos_rpc` output with the core `copy` and/or `assemble` modules.

**Comment by CodeTechies** [comment]
Hi Stacy,

Thanks for your reply, 

Sometimes to keep a single file record after the maintenance it's handy to have a single file for all output and it's easier to compare files manually the pre activity and post activity logs if required, but it would be great if had this feature, currently we are doing  using python  with paramiko and call in Ansible.

 Assemble method result is similar to dest, filename not inserted.

**Comment by stacywsmith** [comment]
Sorry. I don't have a setup to try this out at the moment, but maybe you could do something like this...

Assuming `/mytemplates/foo.j2` has this content:
```
{% for item in response.results %}
Command: {{ item.command }}
Output:
{{ item.stdout }}


{% endfor %}
```

Try a playbook like this:
```
---
- name: Examples of juniper_junos_command
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Execute three commands.
      juniper_junos_command:
        commands:
          - "show version"
          - "show system uptime"
          - "show interface terse"
      register: response
    - name: Print the command and output to a single file.
      template:
        src: /mytemplates/foo.j2
        dest: /tmp/{{ inventory_hostname }}_output.txt
```
