### ISSUE TITLE
Feature Request: "pkg_set" for Ansible "juniper_junos_software.py" module.

### ISSUE THREAD

**Issue by mahbubakhanda** [Juniper/ansible-junos-stdlib#436]
Issue Type
------
 - Feature Idea

Module Name
------

"juniper_junos_software.py"

Juniper.Junos role and Python libraries version

ansible 2.7.0
  config file = /project/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]

```
ansible==2.7.0
asn1crypto==0.24.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
beautifulsoup4==4.6.0
bs4==0.0.1
certifi==2017.4.17
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
configparser==3.5.0
CouchDB==1.2
cryptography==2.3.1
docker==2.4.2
docker-py==1.10.6
docker-pycreds==0.3.0
enum34==1.1.6
future==0.16.0
icdiff==1.9.1
idna==2.5
ipaddress==1.0.22
Jinja2==2.10
jsnapy==1.3.2
junos-eznc==2.2.0
junos-netconify==1.0.2
jxmlease==1.0.1
lxml==3.8.0
MarkupSafe==1.0
ncclient==0.6.3
netaddr==0.7.19
paramiko==2.4.2
pyasn1==0.4.4
pycparser==2.19
PyNaCl==1.3.0
pyparsing==2.2.2
pyserial==3.4
python-gitlab==0.21.2
PyYAML==3.13
requests==2.18.1
scp==0.11.0
selectors2==2.0.1
six==1.10.0
urllib3==1.21.1
websocket-client==0.53.0
```
module: juniper_junos_software
version_added: "2.0.0" # of Juniper.junos role

OS / Environment
------

QFX5100
EX4300
Junos: 17.3R3-S4.2
Junos: 15.1R7-S4

Summary
------
"pkg_set" for Mixed Mode Virtual Chassis upgrade:

Request for "pkg_set" feature for "juniper_junos_software.py" module. This "pkg_set" is already available with PyEZ.

When upgrading a Mixed Mode Virtual Chassis we need to specify more than one image suitable for each member switches in the VC. Current "juniper_junos_software.py" only support one image/image location. So a feature like "pkg_set" in PyEZ will enable listing multiple images.

Steps to reproduce
------

```yaml

- name: Upgrading the QFX5100+EX4300 VC
      juniper_junos_software:
        host: "{{ inventory_hostname  }}"
        user: "{{ credentials.username }}"
        passwd: "{{ credentials.password }}"
        version: "{{ swversion }}"
        local_package: "{{ playbook_dir }}/junos_images/{{ packagename }}"
        remote_package: "/var/tmp/{{ packagename }}"

## Need "local_pkg_set" or "remote_pkg_set" to specify a list of Junos Images.

```

Expected results

```
same result as cli command "request system software add set [ image1_path image2_path ]'"
```
Actual results
------

```

```
