### ISSUE TITLE
juniper_junos_software.py - Version check needed for Special releases/Cloud releases and package type junos-evo. 

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#447]
Issue Type
------

 - Bug Report

Module Name
------
-juniper_junos_software

Juniper.Junos role and Python libraries version

```
  ansible 2.8.2
  config file = /Users/mamathac/WORK/Ansible/virt/pb/ansible.cfg
  configured module search path = [u'/Users/mamathac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

pip list
Package                                Version
-------------------------------------- --------
junos-eznc                             2.2.1
jxmlease                               1.0.1
paramiko                               2.4.2
ncclient                              0.6.6
```

OS / Environment
------
Model: mx240
Junos: 18.3R1-S5

Summary
------
juniper_junos_software Module does a version check for image install and skips it if the image string matches the image currently installed on the router.

In problem build (18.3R1-S5), the check seems to have failed.
Also Support to Evo platform needed for string comparison.
Evo platform = junos-evo*

Steps to reproduce
------
Run juniper_junos_software on a device runnning with 18.3R1-S5 to load the same image.

```
---
- name: Testing Juniper Junos Core Modules
  hosts: [SINGLE]
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    #ansible_python_interpreter: "/usr/bin/python2.7"

  tasks:
   - name: Install Junos OS package
     juniper_junos_software:
        host={{ inventory_hostname }}
        user={{user}}
        passwd={{password}}
        reboot=yes
        port=830
        version={{ OS_version }}
        package={{ pkg_dir }}/{{ OS_package }}
        validate=true
        logfile=software.log
     register: sw
     notify:
     - wait_reboot
     tags:
        - ans_install_os_module
  vars:
   wait_time: 3600
   pkg_dir: .
   OS_version: 18.3R1
   OS_package: junos-install-mx-x86-64-18.3R1-S5.tgz
   log_dir: /var/log/ansible

  handlers:
    - name: wait_reboot
      wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
      when: not sw.check_mode

```

Expected results
```
Expected result: 
Image install should skip as the version is same.

```
Actual results
------
```
Image gets loaded on the device even if the device already has the same version.

```

**Comment by dineshbaburam91** [comment]
Hi Mamatha,

There is a difference in Junos and EVO version format.

# Junos version
```
{master}
root@mx> show version
Hostname: MX
Model: mx240
Junos: 22.1R1.4
```

# EVO version

```
root@scapa> show version
Hostname: scapa
Model: ptx10008
Junos: 22.3-202204241910.0-EVO
Yocto: 3.0.2
```

Kindly provide the correctly formatted version in the ansible-playbook to check the current version of the device and target version.

```
  tasks:
    - name: Upgrade Junos OS from package copied at device
      software:
        host: "10.x.x.x"
        user: "user"
        passwd: "pass"
        port: "22"
        version: "22.3-202204241910.0-EVO"
        timeout: 900
        local_package: "/ansible/junos-evo-install-ptx-chassis-x86-64-22.3-202204241910.0-EVO.iso"
      register: response
```

It will do the installation if the current and target version not matched

```
ok: [vm1] => {
    "response": {
        "changed": false,
        "check_mode": false,
        "failed": false,
        "msg": "Current version on 22.3-202204241910.0-EVO: re0 same as Targeted version: 22.3-202204241910.0-EVO.\nCurrent version on 22.3-202204241910.0-EVO: re1 same as Targeted version: 22.3-202204241910.0-EVO.\n"
    }
}
```
