### ISSUE TITLE
dest_dir option on juniper_junos_command sometimes does not return full JSON object when JSON format is specified

### ISSUE THREAD

**Issue by zerowaitstate** [Juniper/ansible-junos-stdlib#477]
Issue Type
------

 - Bug Report

Module Name
------

juniper_junos_command

Juniper.Junos role and Python libraries version

```
ansible 2.9.2
  config file = /home/dwaites/Development/bisd-playbooks/ansible.cfg
  configured module search path = [u'/home/dwaites/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

apturl==0.5.2
arrow==0.15.2
asn1crypto==0.24.0
attrs==19.3.0
aws-lambda-builders==0.5.0
aws-sam-cli==0.23.0
aws-sam-translator==1.15.1
awscli==1.16.81
awsebcli==3.14.8
beautifulsoup4==4.6.0
binaryornot==0.4.4
blessed==1.15.0
boto3==1.10.5
botocore==1.13.5
Brlapi==0.6.6
cached-property==1.5.1
cement==2.8.2
certifi==2018.11.29
chardet==3.0.4
chevron==0.13.1
Click==7.0
colorama==0.3.9
command-not-found==0.3
cookiecutter==1.6.0
cryptography==2.1.4
cupshelpers==1.0
dateparser==0.7.2
defer==1.0.6
distro-info===0.18ubuntu0.18.04.1
docker==4.1.0
docker-compose==1.21.2
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
fido2==0.8.1
Flask==1.0.4
future==0.18.1
html5lib==0.999999999
httpie==0.9.8
httplib2==0.9.2
idna==2.6
importlib-metadata==0.23
itsdangerous==1.1.0
Jinja2==2.10.3
jinja2-time==0.2.0
jmespath==0.9.3
jsonschema==3.1.1
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
lxml==4.2.1
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
more-itertools==7.2.0
netifaces==0.10.4
oauth==1.0.1
olefile==0.45.1
pathspec==0.5.5
pexpect==4.2.1
Pillow==5.1.0
pipenv==2018.11.26
ply==3.11
poyo==0.5.0
prompt-toolkit==1.0.15
protobuf==3.0.0
pyasn1==0.4.4
pycairo==1.16.2
pycountry==17.5.14
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyOpenSSL==17.5.0
pyRFC3339==1.0
pyrsistent==0.15.5
pyscard==1.9.6
PySocks==1.6.5
python-apt==1.6.4
python-dateutil==2.7.5
python-debian==0.1.32
pytz==2018.3
pyusb==1.0.0
pyxattr==0.6.0
pyxdg==0.25
PyYAML==5.1.2
redis==3.2.1
regex==2019.8.19
reportlab==3.4.0
requests==2.22.0
requests-unixsocket==0.1.5
rsa==3.4.2
s3transfer==0.2.1
SecretStorage==2.3.1
semantic-version==2.5.0
serverlessrepo==0.1.9
setproctitle==1.1.10
simplejson==3.13.2
six==1.11.0
ssh-import-id==5.7
streamlink==0.10.0
system-service==0.3
systemd-python==234
termcolor==1.1.0
texttable==0.9.1
tzlocal==2.0.0
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
virtualenv==16.1.0
virtualenv-clone==0.4.0
wadllib==1.3.2
wcwidth==0.1.7
webencodings==0.5
websocket-client==0.54.0
Werkzeug==0.16.0
whichcraft==0.6.1
xkit==0.0.0
xonsh==0.6.0
youtube-dl==2018.3.14
yubikey-manager==3.1.0
zipp==0.6.0
zope.interface==4.3.2

- Juniper.junos, 2.3.0
```

OS / Environment
------

Ubuntu 18.04 running ansible playbook against EX3300 switch running 15.1R5.5

Summary
------

When using the juniper_junos_command module with the dest_dir option and specifying the format as json, the output file generated sometimes looks like this:

```
<Element lldp-neighbors-information at 0x7ff22a3e7870>
```
This does not always happen; sometimes correct JSON is returned.  When the text format is used, expected data is returned.  This appears to be related to the size of the output.

Steps to reproduce
------

```yaml
---

- name: Get facts
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    connection_settings:
      port: 830
      host: "{{ ansible_host }}"
      user: "{{ username }}"
      passwd: "{{ password }}"
      timeout: 120
  vars_prompt:
    - name: username
      prompt: Junos username
      private: no
    - name: password
      prompt: Junos password
      private: yes
  tasks:
    - include: netconf_wait.yaml
    - name: show lldp neighbors command
      juniper_junos_command:
        commands:
          - "show lldp neighbors"
        provider: "{{ connection_settings }}"
        dest_dir: "./outputs"
        formats: json
        return_output: no


```

Expected results

files that looks like this:
```
{u'lldp-neighbors-information': [{u'attributes': {u'junos:style': u'brief'}, u'lldp-neighbor-information': [{u'lldp-local-parent-interface-name': [{u'data': u'-'}], u'lldp-remote-port-description': [{u'data': u'xe-0/1/1.0'}], u'lldp-remote-system-name': [{u'data': u'008-BGYM-3300'}], u'lldp-remote-chassis-id-subtype': [{u'data': u'Mac address'}], u'lldp-remote-chassis-id': [{u'data': u'30:b6:4f:b9:83:c0'}], u'lldp-local-interface': [{u'data': u'xe-0/1/0.0'}]}, {u'lldp-local-parent-interface-name': [{u'data': u'-'}], u'lldp-remote-port-description': [{u'data': u'eth0'}], u'lldp-remote-system-name': [{u'data': u'008-AP105'}], u'lldp-remote-chassis-id-subtype': [{u'data': u'Mac address'}], u'lldp-remote-chassis-id': [{u'data': u'74:3e:2b:30:a2:c0'}], u'lldp-local-interface': [{u'data': u'ge-0/0/11.0'}]}]}]}
```
Actual results
------

```
<Element lldp-neighbors-information at 0x7ff22a3e7870>
```
