### ISSUE TITLE
Monitor-failures information is missing in juniper_junos_facts output

### ISSUE THREAD

**Issue by EpiqSty** [Juniper/ansible-junos-stdlib#482]
Issue Type
------
 - Bug Report
 - Feature Idea

Module Name
------
juniper_junos_facts

Juniper.Junos role and Python libraries version

```
$ ansible --version
ansible 2.9.4
  config file = /mnt/c/work/SYS/ansible-network/ansible.cfg
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
$ ansible-galaxy list
- Juniper.junos, 2.3.0
```

OS / Environment
------
15.1X49-D170.4

Summary
------
Monitor-failures information is missing in juniper_junos_facts output

Steps to reproduce
------

```yaml
---
- name: Gather facts from Junos devices
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Gather Junos facts with no configuration
      juniper_junos_facts:
```

Expected results
As ```ansible_facts.junos.srx_cluster_redundancy_group``` is replicating information from ```show chassis cluster status``` CLI command, I would expect something like:

```
    srx_cluster_redundancy_group:
      '0':
        cluster_id: '1'
        failover_count: '1'
        node0:
          failover_mode: 'no'
          preempt: 'no'
          priority: '100'
          status: secondary
          monitor_failures: None
        node1:
          failover_mode: 'no'
          preempt: 'no'
          priority: '200'
          status: primary
          monitor_failures: None
```
in case of such CLI output:
```
> show chassis cluster status                       
Monitor Failure codes:
    CS  Cold Sync monitoring        FL  Fabric Connection monitoring
    GR  GRES monitoring             HW  Hardware monitoring
    IF  Interface monitoring        IP  IP monitoring
    LB  Loopback monitoring         MB  Mbuf monitoring
    NH  Nexthop monitoring          NP  NPC monitoring
    SP  SPU monitoring              SM  Schedule monitoring
    CF  Config Sync monitoring      RE  Relinquish monitoring

Cluster ID: 1
Node   Priority Status         Preempt Manual   Monitor-failures

Redundancy group: 0 , Failover count: 1
node0  100      secondary      no      no       None
node1  200      primary        no      no       None
```
Actual results
------

```
    srx_cluster_redundancy_group:
      '0':
        cluster_id: '1'
        failover_count: '1'
        node0:
          failover_mode: 'no'
          preempt: 'no'
          priority: '100'
          status: secondary
        node1:
          failover_mode: 'no'
          preempt: 'no'
          priority: '200'
          status: primary
```
