### ISSUE TITLE
Unable to use junos_scp module

### ISSUE THREAD

**Issue by jdratlif** [Juniper/ansible-junos-stdlib#522]
Issue Type
------
 - Bug Report

Module Name
------
junos_scp

```
# ansible --version
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

# pip3 freeze
ganalytics==0.2.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-redis==5.0.0
azure-mgmt-resource==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
Babel==2.5.1
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.7
boto==2.47.0
boto3==1.9.223
botocore==1.12.253
cachetools==3.1.1
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
colorama==0.4.3
cryptography==2.8
decorator==4.4.1
docutils==0.15.2
dogpile.cache==0.9.0
future==0.18.2
google-auth==1.6.2
gpg==1.10.0
humanfriendly==4.18
idna==2.8
iso8601==0.1.12
isodate==0.6.0
Jinja2==2.10.1
jmespath==0.9.4
jsonpatch==1.24
jsonpointer==2.0
junos-eznc==2.5.3
keystoneauth1==3.18.0
knack==0.3.3
lxml==4.4.2
MarkupSafe==1.1.1
msrest==0.6.1
msrestazure==0.5.0
munch==2.5.0
ncclient==0.6.3
netaddr==0.7.19
netifaces==0.10.9
ntc-templates==1.5.0
ntlm-auth==1.4.0
oauthlib==3.1.0
openstacksdk==0.37.0
os-service-types==1.7.0
ovirt-engine-sdk-python==4.3.0
packaging==19.2
paramiko==2.7.1
pbr==5.4.4
ply==3.9
psutil==5.4.3
psycopg2==2.7.5
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser==2.19
pycurl==7.43.0.1
Pygments==2.5.2
PyJWT==1.7.1
pykerberos==1.2.1
PyNaCl==1.3.0
pyOpenSSL==19.1.0
pyparsing==2.4.5
pyserial==3.4
python-dateutil==2.8.1
pytz==2017.2
pyvmomi==6.7.3
pywinrm==0.3.0
PyYAML==5.2
requests==2.22.0
requests-credssp==1.0.2
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
rpm==4.14.2
s3transfer==0.2.1
scp==0.13.2
selectors2==2.0.1
selinux==2.9
six==1.13.0
stevedore==1.31.0
supervisor==4.2.0
tabulate==0.8.2
textfsm==1.1.0
transitions==0.8.2
urllib3==1.25.7
virtualenv==16.7.10
xmltodict==0.12.0
yamlordereddictloader==0.4.0
```

OS / Environment
------

Model: mx960
Junos: 17.3R3.10

Summary
------

I cannot use the junos_scp module.
It says I must provide a host, but if I do, it tells me providing a host is deprecated and gives me a confusing error.

Steps to reproduce
------

```yaml
---
- name: Place a certificate on a router
  hosts: '{{ my_hosts | default("all") }}'
  connection: local
  gather_facts: no

  tasks:
    - name: copy CA certificate to router
      junos_scp:
        src: '/tmp/ca.cert'
        dest: '/var/tmp'
```

Expected results

```
I expected the file to be copied to the router.
```

Actual results
------

```
TASK [copy CA certificate to router] *******************************************
13:49:55
fatal: [mx960-1]: FAILED! => {"changed": false, "msg": "You must provide either 'host' or 'sock_fd' value"}
fatal: [mx960-2]: FAILED! => {"changed": false, "msg": "You must provide either 'host' or 'sock_fd' value"}
```

```
TASK [copy CA certificate to router] *******************************************
13:46:15
[DEPRECATION WARNING]: Param 'host' is deprecated. See the module docs for more
 information. This feature will be removed in version 2.9. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [mx960-2]: FAILED! => {"changed": false, "msg": "fail_json() takes 1 positional argument but 2 were given"}
fatal: [mx960-1]: FAILED! => {"changed": false, "msg": "fail_json() takes 1 positional argument but 2 were given"}
```

**Comment by jacp9** [comment]
I believe this module only works with values from within `provider` dict, like shown below. It won't work any other way. You may want to remove `remote_src: yes` for your particular use case.
   ```
 - name: Download Logs
      junipernetworks.junos.junos_scp:
        remote_src: yes
        src: "{{ junos_tgz }}"
        dest: "{{ local_tgz }}"
        provider:
          host: "{{ ansible_host }}"
          password: "{{ ansible_password }}"
          username: "{{ ansible_user }}"
          port: 22
          timeout: 300
```
