### ISSUE TITLE
Extend junos_get_facts savedir to save facts when using netconf

### ISSUE THREAD

**Issue by shermdog** [Juniper/ansible-junos-stdlib#53]
At current the savedir variable is only used for netconify.  Extend this to support both modes.

Temporary work around:

```yaml
---
  - name: Get Device Facts
    hosts: all
    connection: local
    gather_facts: no

    tasks:
     - name: Checking NETCONF connectivity
       wait_for: host={{ inventory_hostname }} port=22 timeout=5

     - name: Retrieve information from devices running Junos OS
       junos_get_facts:
        host={{ inventory_hostname }}
        user=user
        passwd=passwd
       register: junos

     - name: version
       debug: msg="{{ junos.facts }}"

     - copy: content="{{ junos }}" dest=./{{ inventory_hostname }}.json
```
