### ISSUE TITLE
Add a new option to juniper_junos_software (collection juniper.device)

### ISSUE THREAD

**Issue by hrv231** [Juniper/ansible-junos-stdlib#549]
Issue Type
------

 - Feature Idea

Module Name
------

juniper.device collection and Python libraries version

```
ansible 2.10.5
  config file = /home/user1/ansible/ansible/ansible.cfg
  configured module search path = ["/home/user1/ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/ansible/ansible/library'"]
  ansible python module location = /home/user1/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user1/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]


juniper.device         0.1.0 
```

OS / Environment
------
ex3400
18.1R3.3

Summary
------
When I try to upgrade using the modules, for the ex2300 and the ex3400 there is no space available and it throws an error.
There are plenty of reports on this:
https://kb.juniper.net/InfoCenter/index?page=content&id=KB31198&actp=METADATA
https://kb.juniper.net/InfoCenter/index?page=content&id=KB34652&actp=LIST_RECENT
https://community.juniper.net/communities/community-home/digestviewer/viewthread?MID=71036#bm833e1af2-42df-4b21-9201-0f7dd1a143ca

Steps to reproduce
------

We need another feature like **cleanfs: yes** , but this new feature will run "_request system snapshot delete snap*_" as said in the url above.
So.. in my playbook I could use it or not, example:

```yaml
    - name: INSTALL Junos OS package
      juniper_junos_software:
        reboot: yes
        checksum: "{{ checksum_file }}"
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
       cleanfs: yes
       cleansnapshots: yes
```

Expected results

```
Based on the documentation from here
https://junos-ansible-modules.readthedocs.io/en/2.4.3/juniper_junos_software.html
Add a 4A step, this step will say:
If the cleansnapshots option is true, the default is false, then perform the equivalent of the request system snapshot delete snap* CLI command.
```
Actual results
------

This is a request of a new feature to add to the juniper_junos_software that I believe will help a lot of users who have ex2300 and ex3400 like me.

```
There is another ticket open that this might be related:
https://github.com/Juniper/ansible-junos-stdlib/issues/484

```
