### ISSUE TITLE
Update Docs to Include fully-qualified collection name

### ISSUE THREAD

**Issue by itdependsnetworks** [Juniper/ansible-junos-stdlib#553]
------

 - Documentation Report

Module Name
------
Ansible Collection

juniper.device collection and Python libraries version
```
N/A with Docs
```

OS / Environment
------
```
N/A with Docs
```
Summary
------
The documents refer to using a play level keyword of [collection](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#play). This is not generally the recommended approach, instead using an Ansible FQCN is recommended, even if verbose at times. I think this is especially relevant here for potential name space issues, as well as mind tracking issues. It is not clear to the reader that `config` or `software` are specific to the `juniper.device`. The recommendation is to update documentation to reenforce that with documentation. As true with many of us in the open source world, I have far too many commitments to take this on, so no issues to close this with/without bias :) 

Steps to reproduce
------
N/A with docs

Expected results
```
- name: Install Junos OS
  hosts: dc1
  collections:
  connection: local

  tasks:

    - name: Install Junos OS package
      juniper.device.software:
        reboot: yes
        version: "{{ OS_version }}"
        package: "{{ pkg_dir }}/{{ OS_package }}"
        logfile: "{{ log_dir }}/software.log"
      register: sw
      notify:
        - wait_reboot
```
Actual results
------

```
- name: Install Junos OS
  hosts: dc1
  collections:
    - juniper.device
  connection: local

  tasks:

    - name: Install Junos OS package
      software:
        reboot: yes
        version: "{{ OS_version }}"
        package: "{{ pkg_dir }}/{{ OS_package }}"
        logfile: "{{ log_dir }}/software.log"
      register: sw
      notify:
        - wait_reboot
```
