### ISSUE TITLE
get interface vlan information from device running old version

### ISSUE THREAD

**Issue by hrv231** [Juniper/ansible-junos-stdlib#554]
Issue Type
------

 - Help

Module Name
------

`juniper.device.rpc`

juniper.device collection and Python libraries version

```
ansible 2.10.5
  config file = /home/user1/ansible/ansible/ansible.cfg
  configured module search path = ["/home/user1/ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/ansible/ansible/library'"]
  ansible python module location = /home/user1/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user1/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]


juniper.device         0.1.0 
```

OS / Environment
------

ex3200
JUNOS 12.3R7.7 built 2014-06-12

Summary
------

I'm trying to gather all addresses from each interface, I was able to do it for almost all interfaces except interface **vlan**.

Steps to reproduce
------

```yaml
    - name: run rpc on the remote device
      juniper.device.rpc:
        rpcs: get-config
        formats: xml
        filter: "configuration/interfaces/interface"
        kwargs: "interface_name=vlan"
      register: test

    - local_action: copy content={{ test.parsed_output | to_nice_json }} dest=/home/user1/ansible/ansible/{{inventory_hostname}}.txt

    - name: Print response
      debug:
        msg: "{{item.name}}.{{item.unit.name}} has IP {{item.unit.family.inet.address.name|default(omit) }}"
      loop: "{{ test.parsed_output.configuration.interfaces.interface|default(omit) }}"
      when: item.unit.family  | regex_search('inet')
      ignore_errors: yes
```

Expected results

```
The result is that I get the configuration parsed in json, very nice, but when I get to the interface "vlan" I get a dictionary inside another dictionary, and I don't know how to pull that information.
I can pull the information from interface "me0" though.

```
Actual results
------

```
This is partial output of my json:
{
    "configuration": {
        "interfaces": {
            "interface": [
                 {
                    "name": "me0",
                    "unit": {
                        "family": {
                            "inet": {
                                "address": {
                                    "name": "10.96.12.1/17"
                            }
                        },
                        "name": "0"
                    }
                },
                {
                    "name": "vlan",
                    "unit": [
                        {
                            "description": "Default VLAN",
                            "family": {
                                "inet": {
                                    "address": [
                                        {
                                            "name": "10.96.1.1/16"
                                        },
                                        {
                                            "name": "19.26.10.1/24"
                                        }
                                    ]
                                },
                                "inet6": {
                                    "address": {
                                        "name": "2000:aa00:0400:1::1/64"
                                    }
                                }
                            },
                            "name": "1"
                        },
                        {
                            "description": "Public Wifi",
                            "family": {
                                "inet": {
                                    "address": {
                                        "name": "10.96.128.1/17"
                                    }
                                },
                                "inet6": {
                                    "address": {
                                        "name": "2000:aa00:0400:3::1/64"
                                    }
                                }
                            },
                            "name": "3"
                        },
                        {
                            "family": {
                                "inet": {
                                    "address": {
                                        "name": "10.196.16.1/20"
                                    }
                                }
                            },
                            "name": "16"
                        },
                        {
                            "family": {
                                "inet": {
                                    "address": {
                                        "name": "10.196.32.1/20"
                                    }
                                }
                            },
                            "name": "32"
                        },
                        {
                            "description": "WIRED_48",
                            "family": {
                                "inet": {
                                    "address": {
                                        "name": "10.196.48.1/20"
                                    }
                                }
                            },
                            "name": "48"
                        }
                    ]
                }
            ]
        }
    }
}
```
