### ISSUE TITLE
'JuniperJunosModule' object has no attribute '_pyez_conn'

### ISSUE THREAD

**Issue by ric79** [Juniper/ansible-junos-stdlib#575]
I'm reopening the issue because I'm in a fresh install and I still get the old error

Issue Type
 - Bug Report

Environment
------
```
$ more /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

$ ansible --version
...
ansible [core 2.11.6]
  python version = 3.7.4 (default, Aug 29 2019, 11:06:11) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
  jinja version = 3.0.2
  libyaml = True
  
$ pip list |grep junos
junos-eznc            2.6.3


$ ansible-galaxy collection list

# /home/.../.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     2.4.0
ansible.utils         2.4.2
juniper.device        1.0.1
junipernetworks.junos 2.6.0

# /home/.../python_envs/cgnat-upgrade-env/lib/python3.7/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
...
junipernetworks.junos         2.6.0
...
```

Summary
------
I'm not able to run this simple playbook

```
- name: Get device information
  hosts: MX1-NAT44
  connection: juniper.device.pyez
  gather_facts: no
  vars:
    user: "...."
    passed: "...."
    
  tasks:  
               
    - name: Retrieve facts from devices running Junos OS
      juniper.device.facts:  
        savedir: "{{ playbook_dir }}"
```

       
I get

TASK [Retrieve facts from devices running Junos OS] **********************************************************************************
task path: /home/.../.../prova2.yaml:23
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'JuniperJunosModule' object has no attribute '_pyez_conn'
fatal: [MX1-NAT44]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/.../.ansible/tmp/ansible-local-25981d6hz01ys/ansible-tmp-1636464981.854459-25989-20984106911471/AnsiballZ_facts.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/.../.ansible/tmp/ansible-local-25981d6hz01ys/ansible-tmp-1636464981.854459-25989-20984106911471/AnsiballZ_facts.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/.../.ansible/tmp/ansible-local-25981d6hz01ys/ansible-tmp-1636464981.854459-25989-20984106911471/AnsiballZ_facts.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_juniper.device.facts_payload_4lzu1glw/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py\", line 369, in <module>\n  File \"/tmp/ansible_juniper.device.facts_payload_4lzu1glw/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/modules/facts.py\", line 322, in main\n  File \"/tmp/ansible_juniper.device.facts_payload_4lzu1glw/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 599, in __init__\n  File \"/tmp/ansible_juniper.device.facts_payload_4lzu1glw/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 726, in fail_json\n  File \"/tmp/ansible_juniper.device.facts_payload_4lzu1glw/ansible_juniper.device.facts_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1172, in close_configuration\nAttributeError: 'JuniperJunosModule' object has no attribute '_pyez_conn'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Riccardo

**Comment by ric79** [comment]
Sorry found the problem in the inventory.


inventory.yaml
```
all:
  hosts:
    
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    
    cgnat_totp:
      hosts:  
        MX1-NAT44:
        MX2-NAT44:
      vars:
        foo2: 1
      
  vars:
    ansible_python_interpreter: ~/..../bin/python3.7
```

Final playbook:
```
- name: Get device information
  hosts: MX1-NAT44
  connection: local
  gather_facts: no
  vars:
    user: "..."
    passwd: "---"

  collections:
    - juniper.device
    
  tasks:  
               
    - name: Retrieve facts from devices running Junos OS
      facts:  
        savedir: "{{ playbook_dir }}"

    - name: Get hardware inventory
      juniper.device.command:
        commands: "show chassis hardware"
        dest_dir: "{{ playbook_dir }}" 
```

Rr
