### ISSUE TITLE
Implementation 'action: "shutdown"' in module juniper.device for Juniper devices running VMHOST

### ISSUE THREAD

**Issue by biepio** [Juniper/ansible-junos-stdlib#587]
- Feature Idea

Module Name
------

juniper.device collection and Python libraries version

Summary
------

Could you implement in this module working 'action: "shutdown"' for Juniper devices running VMHOST ? Currently for VMHOST only 'action: "reboot"' working correctly. For 'normal' Junos both actions work correctly.

Steps to reproduce
------

```yaml

---
 
- name: Reboot VM Hosts
  hosts: po_vmhost
  connection: local
  gather_facts: no
  tasks:
          
  - name: Reboot VM Hosts
    juniper.device.system:
      action: "reboot"
#     action: "shutdown"
      vmhost: True
      all_re: True
    register: result
 
  - name: Print result
    debug:
      var: result 


```

Expected results

```
Power-off Juniper device running VMHOST
```
Actual results
------

```
FAILED! => {"changed": false, "msg": "The vmhost option can only be used when the action option has the value \"reboot\"."}
```
