### ISSUE TITLE
Command module cannot retrieve configuration in xml form

### ISSUE THREAD

**Issue by moophat** [Juniper/ansible-junos-stdlib#601]
Issue Type
------

 - Bug Report
Module Name
------

juniper.device collection and Python libraries version
------

```
ansible 2.8.0
Py 3.7.5
juniper.device would have this issue regardless of version - as I checked the code
```

OS / Environment
------

Junos version 15.1
Junos version 20.4

Summary
------

The command module would execute the requested command line in the rpc form
`
<command format=xml>
show something here
<command>
`
However Junos itself would not return the correct format if the command is "show configuration". Configuration must be achieved using the "get-config" rpc. And even in this case 

Steps to reproduce
------

Create a playbook using the command module, specify
- format as xml/json
- the command list include "show configuration" command 

```
- name: test collect xml config
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  vars:
    format: "xml"
    command_list:
      - "show configuration"

  pre_tasks:
    - name: "[VARIABLES] - Generate Credential"
      set_fact:
        credential:
          username: juniper
          password: juniper@123
          host: 10.96.10.10
          port: 22
          logdir: "/var/tmp/test_pyez_collect_config_xml"
          level:  INFO
        host: "{{ '{{' }} ansible_host {{ '}}' }}"
      run_once: true
      delegate_to: localhost

  tasks: 
    - name: run show command in device
      juniper_junos_command:
        provider: "{{ credential }}"
        commands: "{{command_list}}"
        display: "{{ format }}"

      register: command_result
      ignore_errors: yes

```

Expected results

```
Configuration xml should be properly returned
```
Actual results
------

```
Only text config was returned 
```

I have patched together a quickfix using the existing code from rpc module. However it will not support xml filter because the command modules itself do not have such input. Let me know if you are open for a PR for this quick hack.
