### ISSUE TITLE
juniper.device.software on ex3400 VC failed with error  Installation failed. Error: RpcTimeoutError

### ISSUE THREAD

**Issue by kevinhuy** [Juniper/ansible-junos-stdlib#609]
Issue Type
------

 - Bug Report

Module Name
------

juniper.device.software

```
ansible [core 2.14.1]
  config file = /home/test/ansible/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/.pyenv/versions/3.10.4/envs/ansible-juniper/lib/python3.10/site-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/test/.pyenv/versions/ansible-juniper/bin/ansible
  python version = 3.10.4 (main, Nov 18 2022, 13:39:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/home/test/.pyenv/versions/3.10.4/envs/ansible-juniper/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True

ansible==7.1.0
ansible-core==2.14.1
bcrypt==4.0.1
cffi==1.15.1
cryptography==39.0.0
Jinja2==3.1.2
junos-eznc==2.6.6
jxmlease==1.0.3
lxml==4.9.2
MarkupSafe==2.1.2
ncclient==0.6.13
netaddr==0.8.0
packaging==23.0
paramiko==3.0.0
pycparser==2.21
PyNaCl==1.5.0
pyparsing==3.0.9
pyserial==3.5
PyYAML==6.0
resolvelib==0.8.1
scp==0.14.4
six==1.16.0
transitions==0.9.0
xmltodict==0.13.0
yamlordereddictloader==0.4.0
```

OS / Environment
------

EX3400 in virtual chassis 
junos version 20.4R1.12
target firmware : 21.4R3.15

Summary
------

While attempting an upgrade from 20.4R1.12 to 21.4R3.15 on an juniper EX3400 VC, juniper.device.software fails with 
"Installation failed. Error: RpcTimeoutError(host: X.X.X.X, cmd: request-package-nonstop-upgrade, timeout: 1800)"

is there a possibility to increase timeout ?

Steps to reproduce
------

```yaml
---
- name: Install Junos OS
  hosts: ex3400.local.dev
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  vars:
    OS_version: "21.4R3.15"
    OS_package: "junos-arm-32-21.4R3.15.tgz"
    pkg_dir: "/images/EX3400"
    log_dir: "{{ playbook_dir }}"
    netconf_port: 22
    wait_time: 3800
  
    
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      juniper.device.software:
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        cleanfs: True
        no_copy: False
        reboot: True
        validate: True
        nssu: True
      register: response
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not response.check_mode

```

Expected results

```

```
Actual results
------

```
The full traceback is:
  File "/tmp/ansible_juniper.device.software_payload_no0yrsmn/ansible_juniper.device.software_payload.zip/ansible_collections/juniper/device/plugins/modules/software.py", line 701, in main
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/utils/sw.py", line 986, in install
    return self.pkgaddNSSU(remote_package, dev_timeout=timeout, **kwargs)
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/utils/sw.py", line 261, in pkgaddNSSU
    rsp = self.rpc.request_package_nonstop_upgrade(
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/home/test/.pyenv/versions/ansible-juniper/lib/python3.10/site-packages/jnpr/junos/device.py", line 842, in execute
    raise EzErrors.RpcTimeoutError(self, rpc_cmd_e.tag, self.timeout)
fatal: [ex3400.local.dev]: FAILED! => {
    "changed": true,
    "check_mode": false,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "cs_passwd": null,
            "cs_user": null,
            "force_host": false,
            "host": "10.60.18.1",
            "huge_tree": false,
            "issu": false,
            "level": null,
            "logdir": "",
            "logfile": "",
            "mode": null,
            "nssu": true,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 22,
            "ssh_config": null,
            "ssh_private_key_file": null,
            "timeout": 10,
            "user": "root",
            "validate": true,
            "vmhost": false
        }
    },
    "msg": "Installation failed. Error: RpcTimeoutError(host: X.X.X.X, cmd: request-package-nonstop-upgrade, timeout: 1800)"
}

```

**Comment by dineshbaburam91** [comment]
You can set the timeout using "timeout" variable in the playbook to avoid RpcTimeError

```
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      juniper.device.software:
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        cleanfs: True
        no_copy: False
        reboot: True
        validate: True
        nssu: True
        timeout: 300
      register: response
      notify:
      - wait_reboot
```
