### ISSUE TITLE
juniper.device.config module with  set system login message " " with "," separated text message replaces "," with  newline 

### ISSUE THREAD

**Issue by chidanandpujar** [Juniper/ansible-junos-stdlib#618]
Issue Type
------

 - Bug Report

Module Name
------

juniper.device collection and Python libraries version

```
ansible-junos-stdlib  v1.0.2-collections
juniper.device.config
junos-eznc            2.6.7+11.g244ab7d5
```

OS / Environment
------

Summary
------

Steps to reproduce
------

```yaml
- hosts: all
  collections:
    - juniper.device
  connection: local
  gather_facts: no
  tasks:
    - name: BannerIssue
      config:
        load: 'set'
        lines: "set system login message \" *******************************************************************************|1. This computer system and each component thereof is, the sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|\"\n\n"
        format: 'set'
```

ansible-junos-stdlib/tests# ansible-playbook test_config_set_login_message.yml 

PLAY [all] ****************************************************************************************************************************************************************

TASK [BannerIssue] ********************************************************************************************************************************************************
fatal: [test]: FAILED! => {"changed": false, "msg": "Failure loading the configuraton: ConfigLoadError(severity: error, bad_element: the, message: error: unknown command)"}

PLAY RECAP ****************************************************************************************************************************************************************
test                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Expected results

```
configuration load should be successful  

/ansible-junos-stdlib/tests# ansible-playbook test_config_set_login_message.yml 

PLAY [all] ****************************************************************************************************************************************************************

TASK [BannerIssue] ********************************************************************************************************************************************************
changed: [test]

PLAY RECAP ****************************************************************************************************************************************************************
test                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```
Actual results
------

```
ansible-junos-stdlib/tests# ansible-playbook test_config_set_login_message.yml 

PLAY [all] ****************************************************************************************************************************************************************

TASK [BannerIssue] ********************************************************************************************************************************************************
fatal: [test]: FAILED! => {"changed": false, "msg": "Failure loading the configuraton: ConfigLoadError(severity: error, bad_element: the, message: error: unknown command)"}

PLAY RECAP ****************************************************************************************************************************************************************
test                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by chidanandpujar** [comment]
Ansible splits  the command with ","  and creates two  separate commands as below and the load of set commands fails with on the device .

            "lines": [
                "set system login message \" *******************************************************************************|1. This computer system and each component thereof is the",
                " sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|\"\n\n"

**Comment by dineshbaburam91** [comment]
The issue is not seen, I can able to load the same configuration via Ansible playbook.

```
  tasks:
    - name: commit configuration
      juniper.device.config:
        load: 'set'
        lines:
            - "set system login message \" *******************************************************************************|1. This computer system and each component thereof is, the sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|\"\n\n"
        diff: True
      register: response
```

```
TASK [Print the lines in the config.] ******************************************************************************************************************
ok: [vm1] => {
    "response": {
        "changed": true,
        "diff": {
            "prepared": "\n[edit system]\n+   login {\n+       message \" *******************************************************************************|1. This computer system and each component thereof is, the sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|\";\n+   }\n"
        },
        "diff_lines": [
            "",
            "[edit system]",
            "+   login {",
            "+       message \" *******************************************************************************|1. This computer system and each component thereof is, the sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|\";",
            "+   }"
        ],
        "failed": false,
        "msg": "Configuration has been: opened, loaded, checked, diffed, committed, closed."
    }
}
```

```
root@# show system login 
message " *******************************************************************************|1. This computer system and each component thereof is, the sole and exclusive property of Tata Consultancy Services Limited (TCSL) and is intended solely for the usage of its employees and authorized clients.Unauthorized access or use will attract appropriate legal action.2. By usig or accessing this System. you expressly consent to:(a) be bound by all policies and regulations of TCSL.(b) be monitored by TCSL or its agents or representatives while you are using or accessing this System (including any data that is transmitted by you).(c) be liable for any loss that may be suffered by TCSL due to your use and or access of this System and fouryou agree to indemnify TCSL against all such losses.3.If fiveyou do not agree to any of the terms above then do not use and/or access this System.*******************************************************************************|";
```
