### ISSUE TITLE
juniper.device.config always performs a commit confirmed operation

### ISSUE THREAD

**Issue by slefol** [Juniper/ansible-junos-stdlib#660]
Issue Type
------
 - Bug Report

Module Name
------
juniper.device.config

juniper.device collection and Python libraries version
```
$ ansible --version
ansible [core 2.16.6]
  config file = /home/ansible/ansible_network/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/ansible-venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/ansible-venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/xxx/ansible-venv/bin/python3)
  jinja version = 3.1.3
  libyaml = True


$ ansible-galaxy collection list
Collection     Version
-------------- -------
ansible.netcommon     6.1.1
ansible.posix         1.5.4
ansible.utils         3.0.0
community.general     8.6.0
juniper.device        1.0.4


$ pip freeze
ansible-core==2.16.6
ansible-pylibssh==1.1.0
jsnapy==1.3.7
junos-eznc==2.7.0
ncclient==0.6.15
netmiko==4.3.0
paramiko==3.4.0
...
```

OS / Environment
------
Model: qfx5120-48y-8c
Junos: 22.2R3-S2.8

Summary
------
the module always performs a commit confirmed operation 

Steps to reproduce
------

```yaml
  tasks :
    - name: SET JUNOS CONFIG
      juniper.device.config:
        load: "set"
        format: "set"
        lines: 'set system login message "This is login message"'
        comment: "comment"
```

Actual results
------
On device, we can see : 
```
# commit confirmed will be rolled back in 30 minutes
```

the behavior is the same if we do not specify the  confirm parameter (like here) or if we specify it with a value (ex: 5 minutes)
