### ISSUE TITLE
<unknown>:1813: SyntaxWarning: invalid escape sequence '\*' emitted during ansible-playbook execution

### ISSUE THREAD

**Issue by chidanandpujar** [Juniper/ansible-junos-stdlib#674]
Issue Type
------
 - Bug Report

Module Name
------
juniper.device
python 3.12

OS / Environment
------
JUNOS Evolved

Summary
------
```
TASK [Test reachability to device using do-not-fragment and rapid] ********************************************************************************************************
<unknown>:1813: SyntaxWarning: invalid escape sequence '\*'
```
Steps to reproduce
------
```
    - name: Test reachability to device using do-not-fragment and rapid
      juniper.device.ping:
        dest: x.x.x.x
        do_not_fragment: false
        rapid: true
        size: 64
        count: 3
        acceptable_percent_loss: 50
      ignore_errors: false
      register: test_ping
````

Actual results
------
```
TASK [Test reachability to device using do-not-fragment and rapid] ********************************************************************************************************
<unknown>:1813: SyntaxWarning: invalid escape sequence '\*'
ok: [x.x.x.x]

```
