### ISSUE TITLE
file_copy module to support sha256checksum and destination file as optional

### ISSUE THREAD

**Issue by dineshbaburam91** [Juniper/ansible-junos-stdlib#724]
The requirement is to support the sha256 checksum and destination file in the file_copy module.

Let's say for example:

```
---
- name: Examples of juniper_device_file_copy
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Copy a log file on a remote device locally
      juniper.device.file_copy:
        remote_dir: /var/log
        local_dir: /tmp
        action: get
        sha254_checksum: True    ------> optional
        file: log.txt
        destination_file : log_dest.txt -------> optional
    - name: Copy a local file into /var/tmp on the remote device
      juniper.device.file_copy:
        remote_dir: /var/tmp
        local_dir: /tmp
        action: put
        sha256_checksum: False
        file: license.txt
        destination_file: log_dest.txt
```
