### ISSUE TITLE
junos_ping and junos_netconf fails with MODULE FAILURE: No start of json char found

### ISSUE THREAD

**Issue by chidanandpujar** [Juniper/ansible-junos-stdlib#754]
```
root@masterhost:~/ansible_modules_redirection_ansible_merger_branch/ansible-junos-stdlib/tests/junipernetworks.junos# cat pb.juniper_junos_ping.yml 
- name: Functional Test - junos_ping module
  hosts: all 
  gather_facts: false
  collections:
    - junipernetworks.junos

  tasks:

    - name: Test reachability to target
      junipernetworks.junos.junos_ping:
        dest: "{{ ansible_ssh_host }}" 
      register: ping_default

    - name: Assert default ping worked
      assert:
        that:
          - ping_default.packet_loss is defined

    - name: Test reachability to target using source and size set
      junipernetworks.junos.junos_ping:
        dest: 1.1.1.1 
        size: 1024
        ttl: 128
      register: ping_source_ttl

    - name: Assert source TTL ping worked
      assert:
        that:
          - ping_source_ttl.packet_loss is defined

    - name: Test unreachability to target using interval
      junipernetworks.junos.junos_ping:
        dest: 1.1.1.1 
        interval: 3
        state: present
      register: ping_absent

    - name: "Assert unreachable ping worked (state: absent)"
      assert:
        that:
          - ping_absent.packet_loss is defined

    - name: Test reachability to target setting count and interface
      junipernetworks.junos.junos_ping:
        dest: 1.1.1.1 
        interface: fxp0
        count: 20
        size: 512
      register: ping_iface

    - name: Assert ping with count/interface worked
      assert:
        that:
          - ping_iface.packet_loss is defined

    - name: Test reachability to target using do-not-fragment and rapid
      junipernetworks.junos.junos_ping:
        dest: 1.1.1.1 
        df_bit: true
        rapid: true
      register: ping_df_rapid

    - name: Assert ping with DF bit and rapid worked
      assert:
        that:
          - ping_df_rapid.packet_loss is defined
```

```
root@masterhost:~/ansible_modules_redirection_ansible_merger_branch/ansible-junos-stdlib/tests/junipernetworks.junos# cat pb.juniper_junos_netconf.yml 
- name: Functional Test - junos_netconf module
  hosts: all 
  gather_facts: false
  connection: network_cli
  collections:
    - junipernetworks.junos

  tasks:
    - name: Enable NETCONF service on port 830
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: present
      register: enable_result

    - name: Assert NETCONF service was enabled
      assert:
        that:
          - enable_result.changed is defined
          - enable_result.commands | length > 0

    - name: Disable NETCONF service
      junipernetworks.junos.junos_netconf:
        state: absent
      register: disable_result

    - name: Assert NETCONF service was disabled
      assert:
        that:
          - disable_result.changed is defined
          - disable_result.commands | length > 0
```

```
root@masterhost:~/ansible_modules_redirection_ansible_merger_branch/ansible-junos-stdlib/tests/junipernetworks.junos# cat ansible.cfg 
[defaults]
INVENTORY = ./inventory
#collections_path=/root/ansible_modules_redirection_ansible_merger_branch/ansible-junos-stdlib/ansible_collections/
host_key_checking = False
no_log = False

[persistent_connection]
connect_timeout = 300
connect_retry_timeout = 300

```

```
root@masterhost:~/ansible_modules_redirection_ansible_merger_branch/ansible-junos-stdlib/tests/junipernetworks.junos# cat inventory_junos 
[junos]
10.220.10.59

[junos:vars]
ansible_network_os=juniper.device.junos
ansible_ssh_user=xyz
ansible_ssh_pass=xyz
ansible_connection=ansible.netcommon.netconf

[all:vars]
ansible_python_interpreter=/usr/bin/python3

```

```

Running pb.juniper_junos_ping.yml

PLAY [Functional Test - junos_ping module] *************************************

TASK [Test reachability to target] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: b"Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)"
fatal: [10.220.10.59]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_junipernetworks.junos.junos_ping_payload_sclr4zkc/ansible_junipernetworks.junos.junos_ping_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 73, in parse_rpc_error\n  File \"src/lxml/etree.pyx\", line 3307, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1995, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1882, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1164, in lxml.etree._BaseParser._parseDoc\n  File \"src/lxml/parser.pxi\", line 633, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 743, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 672, in lxml.etree._raiseParseError\n  File \"<string>\", line 1\nlxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-1452523dkz4fmxf/ansible-tmp-1747296039.3337247-1452527-271962629067225/AnsiballZ_junos_ping.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-1452523dkz4fmxf/ansible-tmp-1747296039.3337247-1452527-271962629067225/AnsiballZ_junos_ping.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-1452523dkz4fmxf/ansible-tmp-1747296039.3337247-1452527-271962629067225/AnsiballZ_junos_ping.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.junos_ping', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.junos_ping', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_junipernetworks.junos.junos_ping_payload_sclr4zkc/ansible_junipernetworks.junos.junos_ping_payload.zip/ansible_collections/juniper/device/plugins/modules/junos_ping.py\", line 290, in <module>\n  File \"/tmp/ansible_junipernetworks.junos.junos_ping_payload_sclr4zkc/ansible_junipernetworks.junos.junos_ping_payload.zip/ansible_collections/juniper/device/plugins/modules/junos_ping.py\", line 200, in main\n  File \"/tmp/ansible_junipernetworks.junos.junos_ping_payload_sclr4zkc/ansible_junipernetworks.junos.junos_ping_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 66, in __rpc__\n  File \"/tmp/ansible_junipernetworks.junos.junos_ping_payload_sclr4zkc/ansible_junipernetworks.junos.junos_ping_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 98, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: b\"Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)\"\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
10.220.10.59               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

```
Running pb.juniper_junos_netconf.yml

PLAY [Functional Test - junos_netconf module] **********************************

TASK [Enable NETCONF service on port 830] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: b"NetconfBase.get() got an unexpected keyword argument 'command'"
fatal: [10.220.10.59]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 73, in parse_rpc_error\n  File \"src/lxml/etree.pyx\", line 3307, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1995, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1882, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1164, in lxml.etree._BaseParser._parseDoc\n  File \"src/lxml/parser.pxi\", line 633, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 743, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 672, in lxml.etree._raiseParseError\n  File \"<string>\", line 1\nlxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-145142781sy14df/ansible-tmp-1747295692.4394693-1451431-258266468726714/AnsiballZ_junos_netconf.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-145142781sy14df/ansible-tmp-1747295692.4394693-1451431-258266468726714/AnsiballZ_junos_netconf.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-145142781sy14df/ansible-tmp-1747295692.4394693-1451431-258266468726714/AnsiballZ_junos_netconf.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.junos_netconf', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.junos_netconf', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/juniper/device/plugins/modules/junos_netconf.py\", line 193, in <module>\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/juniper/device/plugins/modules/junos_netconf.py\", line 176, in main\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/juniper/device/plugins/modules/junos_netconf.py\", line 118, in map_config_to_obj\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 66, in __rpc__\n  File \"/tmp/ansible_junipernetworks.junos.junos_netconf_payload_q5kl6god/ansible_junipernetworks.junos.junos_netconf_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 98, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: b\"NetconfBase.get() got an unexpected keyword argument 'command'\"\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}
```
