### ISSUE TITLE
junos_get_config paths broken with async

### ISSUE THREAD

**Issue by chepazzo** [Juniper/ansible-junos-stdlib#81]
In standard mode, I can use relative paths:

``` yaml
  tasks:
  - name: Fetch Juniper configs
    junos_get_config:
      host="{{ inventory_hostname }}"
      dest="configs/{{ inventory_hostname }}.conf"
      format=text
      user={{ LAB_USER }}
      passwd={{ LAB_PASSWORD }}
      logfile=logs/get_configs.log
    register: config
```

When I invoke async:

``` yaml
  tasks:
  - name: Fetch Juniper configs
    junos_get_config:
      host="{{ inventory_hostname }}"
      dest="configs/{{ inventory_hostname }}.conf"
      format=text
      user={{ LAB_USER }}
      passwd={{ LAB_PASSWORD }}
      logfile=logs/get_configs.log
    async: 45
    poll: 1
    register: config
```

I get the error: 
`msg: Uncaught exception - please report: [Errno 2] No such file or directory: 'configs/<<router>>.conf'
failed: [<<router>>] => {"ansible_job_id": "561876101247.26669", "changed": false, "failed": true, "finished": 1}`

However, if I set full paths: 

``` yaml
  tasks:
  - name: Fetch Juniper configs
    junos_get_config:
      host="{{ inventory_hostname }}"
      dest="/opt/ansible/configs/{{ inventory_hostname }}.conf"
      format=text
      user={{ LAB_USER }}
      passwd={{ LAB_PASSWORD }}
      logfile=/opt/ansible/logs/get_configs.log
    async: 45
    poll: 1
    register: config
```

everything works.
